// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: catalog.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CatalogPageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*CatalogPageRequest_PageId
	//	*CatalogPageRequest_CaptionSafe
	//	*CatalogPageRequest_LayoutName
	Request       isCatalogPageRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogPageRequest) Reset() {
	*x = CatalogPageRequest{}
	mi := &file_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogPageRequest) ProtoMessage() {}

func (x *CatalogPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogPageRequest.ProtoReflect.Descriptor instead.
func (*CatalogPageRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *CatalogPageRequest) GetRequest() isCatalogPageRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *CatalogPageRequest) GetPageId() int32 {
	if x != nil {
		if x, ok := x.Request.(*CatalogPageRequest_PageId); ok {
			return x.PageId
		}
	}
	return 0
}

func (x *CatalogPageRequest) GetCaptionSafe() string {
	if x != nil {
		if x, ok := x.Request.(*CatalogPageRequest_CaptionSafe); ok {
			return x.CaptionSafe
		}
	}
	return ""
}

func (x *CatalogPageRequest) GetLayoutName() string {
	if x != nil {
		if x, ok := x.Request.(*CatalogPageRequest_LayoutName); ok {
			return x.LayoutName
		}
	}
	return ""
}

type isCatalogPageRequest_Request interface {
	isCatalogPageRequest_Request()
}

type CatalogPageRequest_PageId struct {
	PageId int32 `protobuf:"varint,1,opt,name=page_id,json=pageId,proto3,oneof"`
}

type CatalogPageRequest_CaptionSafe struct {
	CaptionSafe string `protobuf:"bytes,2,opt,name=caption_safe,json=captionSafe,proto3,oneof"`
}

type CatalogPageRequest_LayoutName struct {
	LayoutName string `protobuf:"bytes,3,opt,name=layout_name,json=layoutName,proto3,oneof"`
}

func (*CatalogPageRequest_PageId) isCatalogPageRequest_Request() {}

func (*CatalogPageRequest_CaptionSafe) isCatalogPageRequest_Request() {}

func (*CatalogPageRequest_LayoutName) isCatalogPageRequest_Request() {}

type CatalogPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      int32                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Rank          int32                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	Caption       string                 `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	PageName      string                 `protobuf:"bytes,5,opt,name=page_name,json=pageName,proto3" json:"page_name,omitempty"`
	IconColor     int32                  `protobuf:"varint,6,opt,name=icon_color,json=iconColor,proto3" json:"icon_color,omitempty"`
	IconImage     int32                  `protobuf:"varint,7,opt,name=icon_image,json=iconImage,proto3" json:"icon_image,omitempty"`
	OrderNum      int32                  `protobuf:"varint,8,opt,name=order_num,json=orderNum,proto3" json:"order_num,omitempty"`
	Visible       bool                   `protobuf:"varint,9,opt,name=visible,proto3" json:"visible,omitempty"`
	Enabled       bool                   `protobuf:"varint,10,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ClubOnly      bool                   `protobuf:"varint,11,opt,name=club_only,json=clubOnly,proto3" json:"club_only,omitempty"`
	Layout        string                 `protobuf:"bytes,12,opt,name=layout,proto3" json:"layout,omitempty"`
	HeaderImage   string                 `protobuf:"bytes,13,opt,name=header_image,json=headerImage,proto3" json:"header_image,omitempty"`
	TeaserImage   string                 `protobuf:"bytes,14,opt,name=teaser_image,json=teaserImage,proto3" json:"teaser_image,omitempty"`
	SpecialImage  string                 `protobuf:"bytes,15,opt,name=special_image,json=specialImage,proto3" json:"special_image,omitempty"`
	TextOne       string                 `protobuf:"bytes,16,opt,name=text_one,json=textOne,proto3" json:"text_one,omitempty"`
	TextTwo       string                 `protobuf:"bytes,17,opt,name=text_two,json=textTwo,proto3" json:"text_two,omitempty"`
	TextDetails   string                 `protobuf:"bytes,18,opt,name=text_details,json=textDetails,proto3" json:"text_details,omitempty"`
	TextTeaser    string                 `protobuf:"bytes,19,opt,name=text_teaser,json=textTeaser,proto3" json:"text_teaser,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogPage) Reset() {
	*x = CatalogPage{}
	mi := &file_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogPage) ProtoMessage() {}

func (x *CatalogPage) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogPage.ProtoReflect.Descriptor instead.
func (*CatalogPage) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *CatalogPage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CatalogPage) GetParentId() int32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CatalogPage) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *CatalogPage) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *CatalogPage) GetPageName() string {
	if x != nil {
		return x.PageName
	}
	return ""
}

func (x *CatalogPage) GetIconColor() int32 {
	if x != nil {
		return x.IconColor
	}
	return 0
}

func (x *CatalogPage) GetIconImage() int32 {
	if x != nil {
		return x.IconImage
	}
	return 0
}

func (x *CatalogPage) GetOrderNum() int32 {
	if x != nil {
		return x.OrderNum
	}
	return 0
}

func (x *CatalogPage) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *CatalogPage) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CatalogPage) GetClubOnly() bool {
	if x != nil {
		return x.ClubOnly
	}
	return false
}

func (x *CatalogPage) GetLayout() string {
	if x != nil {
		return x.Layout
	}
	return ""
}

func (x *CatalogPage) GetHeaderImage() string {
	if x != nil {
		return x.HeaderImage
	}
	return ""
}

func (x *CatalogPage) GetTeaserImage() string {
	if x != nil {
		return x.TeaserImage
	}
	return ""
}

func (x *CatalogPage) GetSpecialImage() string {
	if x != nil {
		return x.SpecialImage
	}
	return ""
}

func (x *CatalogPage) GetTextOne() string {
	if x != nil {
		return x.TextOne
	}
	return ""
}

func (x *CatalogPage) GetTextTwo() string {
	if x != nil {
		return x.TextTwo
	}
	return ""
}

func (x *CatalogPage) GetTextDetails() string {
	if x != nil {
		return x.TextDetails
	}
	return ""
}

func (x *CatalogPage) GetTextTeaser() string {
	if x != nil {
		return x.TextTeaser
	}
	return ""
}

var File_catalog_proto protoreflect.FileDescriptor

const file_catalog_proto_rawDesc = "" +
	"\n" +
	"\rcatalog.proto\x12\acatalog\"\x82\x01\n" +
	"\x12CatalogPageRequest\x12\x19\n" +
	"\apage_id\x18\x01 \x01(\x05H\x00R\x06pageId\x12#\n" +
	"\fcaption_safe\x18\x02 \x01(\tH\x00R\vcaptionSafe\x12!\n" +
	"\vlayout_name\x18\x03 \x01(\tH\x00R\n" +
	"layoutNameB\t\n" +
	"\arequest\"\xae\x04\n" +
	"\vCatalogPage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x05R\bparentId\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rank\x12\x18\n" +
	"\acaption\x18\x04 \x01(\tR\acaption\x12\x1b\n" +
	"\tpage_name\x18\x05 \x01(\tR\bpageName\x12\x1d\n" +
	"\n" +
	"icon_color\x18\x06 \x01(\x05R\ticonColor\x12\x1d\n" +
	"\n" +
	"icon_image\x18\a \x01(\x05R\ticonImage\x12\x1b\n" +
	"\torder_num\x18\b \x01(\x05R\borderNum\x12\x18\n" +
	"\avisible\x18\t \x01(\bR\avisible\x12\x18\n" +
	"\aenabled\x18\n" +
	" \x01(\bR\aenabled\x12\x1b\n" +
	"\tclub_only\x18\v \x01(\bR\bclubOnly\x12\x16\n" +
	"\x06layout\x18\f \x01(\tR\x06layout\x12!\n" +
	"\fheader_image\x18\r \x01(\tR\vheaderImage\x12!\n" +
	"\fteaser_image\x18\x0e \x01(\tR\vteaserImage\x12#\n" +
	"\rspecial_image\x18\x0f \x01(\tR\fspecialImage\x12\x19\n" +
	"\btext_one\x18\x10 \x01(\tR\atextOne\x12\x19\n" +
	"\btext_two\x18\x11 \x01(\tR\atextTwo\x12!\n" +
	"\ftext_details\x18\x12 \x01(\tR\vtextDetails\x12\x1f\n" +
	"\vtext_teaser\x18\x13 \x01(\tR\n" +
	"textTeaser2P\n" +
	"\aCatalog\x12E\n" +
	"\x0eGetCatalogPage\x12\x1b.catalog.CatalogPageRequest\x1a\x14.catalog.CatalogPage\"\x00B3Z1github.com/himalayo/clusterfuck/api/catalog/protob\x06proto3"

var (
	file_catalog_proto_rawDescOnce sync.Once
	file_catalog_proto_rawDescData []byte
)

func file_catalog_proto_rawDescGZIP() []byte {
	file_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)))
	})
	return file_catalog_proto_rawDescData
}

var file_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_catalog_proto_goTypes = []any{
	(*CatalogPageRequest)(nil), // 0: catalog.CatalogPageRequest
	(*CatalogPage)(nil),        // 1: catalog.CatalogPage
}
var file_catalog_proto_depIdxs = []int32{
	0, // 0: catalog.Catalog.GetCatalogPage:input_type -> catalog.CatalogPageRequest
	1, // 1: catalog.Catalog.GetCatalogPage:output_type -> catalog.CatalogPage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_catalog_proto_init() }
func file_catalog_proto_init() {
	if File_catalog_proto != nil {
		return
	}
	file_catalog_proto_msgTypes[0].OneofWrappers = []any{
		(*CatalogPageRequest_PageId)(nil),
		(*CatalogPageRequest_CaptionSafe)(nil),
		(*CatalogPageRequest_LayoutName)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_proto_depIdxs,
		MessageInfos:      file_catalog_proto_msgTypes,
	}.Build()
	File_catalog_proto = out.File
	file_catalog_proto_goTypes = nil
	file_catalog_proto_depIdxs = nil
}
