// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: friends.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gender int32

const (
	Gender_M Gender = 0
	Gender_F Gender = 1
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "M",
		1: "F",
	}
	Gender_value = map[string]int32{
		"M": 0,
		"F": 1,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_friends_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_friends_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_friends_proto_rawDescGZIP(), []int{0}
}

type GetFriendByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendId      int32                  `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendByIdRequest) Reset() {
	*x = GetFriendByIdRequest{}
	mi := &file_friends_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendByIdRequest) ProtoMessage() {}

func (x *GetFriendByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friends_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendByIdRequest.ProtoReflect.Descriptor instead.
func (*GetFriendByIdRequest) Descriptor() ([]byte, []int) {
	return file_friends_proto_rawDescGZIP(), []int{0}
}

func (x *GetFriendByIdRequest) GetFriendId() int32 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

type GetFriendListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendListRequest) Reset() {
	*x = GetFriendListRequest{}
	mi := &file_friends_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendListRequest) ProtoMessage() {}

func (x *GetFriendListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_friends_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendListRequest.ProtoReflect.Descriptor instead.
func (*GetFriendListRequest) Descriptor() ([]byte, []int) {
	return file_friends_proto_rawDescGZIP(), []int{1}
}

func (x *GetFriendListRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type FriendList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []*Friend              `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendList) Reset() {
	*x = FriendList{}
	mi := &file_friends_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendList) ProtoMessage() {}

func (x *FriendList) ProtoReflect() protoreflect.Message {
	mi := &file_friends_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendList.ProtoReflect.Descriptor instead.
func (*FriendList) Descriptor() ([]byte, []int) {
	return file_friends_proto_rawDescGZIP(), []int{2}
}

func (x *FriendList) GetElements() []*Friend {
	if x != nil {
		return x.Elements
	}
	return nil
}

type Friend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Gender        Gender                 `protobuf:"varint,3,opt,name=gender,proto3,enum=friends.Gender" json:"gender,omitempty"`
	Online        int32                  `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`
	Look          string                 `protobuf:"bytes,5,opt,name=look,proto3" json:"look,omitempty"`
	Motto         string                 `protobuf:"bytes,6,opt,name=motto,proto3" json:"motto,omitempty"`
	Relation      int32                  `protobuf:"varint,7,opt,name=relation,proto3" json:"relation,omitempty"`
	CategoryId    int32                  `protobuf:"varint,8,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	UserId        int32                  `protobuf:"varint,10,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Friend) Reset() {
	*x = Friend{}
	mi := &file_friends_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Friend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friend) ProtoMessage() {}

func (x *Friend) ProtoReflect() protoreflect.Message {
	mi := &file_friends_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friend.ProtoReflect.Descriptor instead.
func (*Friend) Descriptor() ([]byte, []int) {
	return file_friends_proto_rawDescGZIP(), []int{3}
}

func (x *Friend) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Friend) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Friend) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_M
}

func (x *Friend) GetOnline() int32 {
	if x != nil {
		return x.Online
	}
	return 0
}

func (x *Friend) GetLook() string {
	if x != nil {
		return x.Look
	}
	return ""
}

func (x *Friend) GetMotto() string {
	if x != nil {
		return x.Motto
	}
	return ""
}

func (x *Friend) GetRelation() int32 {
	if x != nil {
		return x.Relation
	}
	return 0
}

func (x *Friend) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Friend) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_friends_proto protoreflect.FileDescriptor

const file_friends_proto_rawDesc = "" +
	"\n" +
	"\rfriends.proto\x12\afriends\"3\n" +
	"\x14GetFriendByIdRequest\x12\x1b\n" +
	"\tfriend_id\x18\x01 \x01(\x05R\bfriendId\"0\n" +
	"\x14GetFriendListRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\"9\n" +
	"\n" +
	"FriendList\x12+\n" +
	"\belements\x18\x01 \x03(\v2\x0f.friends.FriendR\belements\"\xf5\x01\n" +
	"\x06Friend\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12'\n" +
	"\x06gender\x18\x03 \x01(\x0e2\x0f.friends.GenderR\x06gender\x12\x16\n" +
	"\x06online\x18\x04 \x01(\x05R\x06online\x12\x12\n" +
	"\x04look\x18\x05 \x01(\tR\x04look\x12\x14\n" +
	"\x05motto\x18\x06 \x01(\tR\x05motto\x12\x1a\n" +
	"\brelation\x18\a \x01(\x05R\brelation\x12\x1f\n" +
	"\vcategory_id\x18\b \x01(\x05R\n" +
	"categoryId\x12\x17\n" +
	"\auser_id\x18\n" +
	" \x01(\x05R\x06userId*\x16\n" +
	"\x06Gender\x12\x05\n" +
	"\x01M\x10\x00\x12\x05\n" +
	"\x01F\x10\x012\x93\x01\n" +
	"\aFriends\x12E\n" +
	"\rGetFriendList\x12\x1d.friends.GetFriendListRequest\x1a\x13.friends.FriendList\"\x00\x12A\n" +
	"\rGetFriendById\x12\x1d.friends.GetFriendByIdRequest\x1a\x0f.friends.Friend\"\x00B3Z1github.com/himalayo/clusterfuck/api/friends/protob\x06proto3"

var (
	file_friends_proto_rawDescOnce sync.Once
	file_friends_proto_rawDescData []byte
)

func file_friends_proto_rawDescGZIP() []byte {
	file_friends_proto_rawDescOnce.Do(func() {
		file_friends_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_friends_proto_rawDesc), len(file_friends_proto_rawDesc)))
	})
	return file_friends_proto_rawDescData
}

var file_friends_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_friends_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_friends_proto_goTypes = []any{
	(Gender)(0),                  // 0: friends.Gender
	(*GetFriendByIdRequest)(nil), // 1: friends.GetFriendByIdRequest
	(*GetFriendListRequest)(nil), // 2: friends.GetFriendListRequest
	(*FriendList)(nil),           // 3: friends.FriendList
	(*Friend)(nil),               // 4: friends.Friend
}
var file_friends_proto_depIdxs = []int32{
	4, // 0: friends.FriendList.elements:type_name -> friends.Friend
	0, // 1: friends.Friend.gender:type_name -> friends.Gender
	2, // 2: friends.Friends.GetFriendList:input_type -> friends.GetFriendListRequest
	1, // 3: friends.Friends.GetFriendById:input_type -> friends.GetFriendByIdRequest
	3, // 4: friends.Friends.GetFriendList:output_type -> friends.FriendList
	4, // 5: friends.Friends.GetFriendById:output_type -> friends.Friend
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_friends_proto_init() }
func file_friends_proto_init() {
	if File_friends_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_friends_proto_rawDesc), len(file_friends_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_friends_proto_goTypes,
		DependencyIndexes: file_friends_proto_depIdxs,
		EnumInfos:         file_friends_proto_enumTypes,
		MessageInfos:      file_friends_proto_msgTypes,
	}.Build()
	File_friends_proto = out.File
	file_friends_proto_goTypes = nil
	file_friends_proto_depIdxs = nil
}
