// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: subscription.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Subscription_GetSubscripitonsForUser_FullMethodName = "/subscription.Subscription/GetSubscripitonsForUser"
	Subscription_AddDuration_FullMethodName             = "/subscription.Subscription/AddDuration"
	Subscription_SetActive_FullMethodName               = "/subscription.Subscription/SetActive"
	Subscription_UserHasSubscription_FullMethodName     = "/subscription.Subscription/UserHasSubscription"
	Subscription_UserClubComposer_FullMethodName        = "/subscription.Subscription/UserClubComposer"
	Subscription_GetSessionSubscriptions_FullMethodName = "/subscription.Subscription/GetSessionSubscriptions"
)

// SubscriptionClient is the client API for Subscription service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscriptionClient interface {
	GetSubscripitonsForUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*Subscriptions, error)
	AddDuration(ctx context.Context, in *DurationRequest, opts ...grpc.CallOption) (*SubscriptionInstance, error)
	SetActive(ctx context.Context, in *ActivationRequest, opts ...grpc.CallOption) (*SubscriptionInstance, error)
	UserHasSubscription(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (*HasSubscriptionResponse, error)
	UserClubComposer(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (*Packet, error)
	GetSessionSubscriptions(ctx context.Context, in *SessionSubscriptionRequest, opts ...grpc.CallOption) (*Subscriptions, error)
}

type subscriptionClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionClient(cc grpc.ClientConnInterface) SubscriptionClient {
	return &subscriptionClient{cc}
}

func (c *subscriptionClient) GetSubscripitonsForUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*Subscriptions, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Subscriptions)
	err := c.cc.Invoke(ctx, Subscription_GetSubscripitonsForUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionClient) AddDuration(ctx context.Context, in *DurationRequest, opts ...grpc.CallOption) (*SubscriptionInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionInstance)
	err := c.cc.Invoke(ctx, Subscription_AddDuration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionClient) SetActive(ctx context.Context, in *ActivationRequest, opts ...grpc.CallOption) (*SubscriptionInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionInstance)
	err := c.cc.Invoke(ctx, Subscription_SetActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionClient) UserHasSubscription(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (*HasSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasSubscriptionResponse)
	err := c.cc.Invoke(ctx, Subscription_UserHasSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionClient) UserClubComposer(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (*Packet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Packet)
	err := c.cc.Invoke(ctx, Subscription_UserClubComposer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionClient) GetSessionSubscriptions(ctx context.Context, in *SessionSubscriptionRequest, opts ...grpc.CallOption) (*Subscriptions, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Subscriptions)
	err := c.cc.Invoke(ctx, Subscription_GetSessionSubscriptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriptionServer is the server API for Subscription service.
// All implementations must embed UnimplementedSubscriptionServer
// for forward compatibility.
type SubscriptionServer interface {
	GetSubscripitonsForUser(context.Context, *User) (*Subscriptions, error)
	AddDuration(context.Context, *DurationRequest) (*SubscriptionInstance, error)
	SetActive(context.Context, *ActivationRequest) (*SubscriptionInstance, error)
	UserHasSubscription(context.Context, *SubscriptionRequest) (*HasSubscriptionResponse, error)
	UserClubComposer(context.Context, *SubscriptionRequest) (*Packet, error)
	GetSessionSubscriptions(context.Context, *SessionSubscriptionRequest) (*Subscriptions, error)
	mustEmbedUnimplementedSubscriptionServer()
}

// UnimplementedSubscriptionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubscriptionServer struct{}

func (UnimplementedSubscriptionServer) GetSubscripitonsForUser(context.Context, *User) (*Subscriptions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscripitonsForUser not implemented")
}
func (UnimplementedSubscriptionServer) AddDuration(context.Context, *DurationRequest) (*SubscriptionInstance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDuration not implemented")
}
func (UnimplementedSubscriptionServer) SetActive(context.Context, *ActivationRequest) (*SubscriptionInstance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetActive not implemented")
}
func (UnimplementedSubscriptionServer) UserHasSubscription(context.Context, *SubscriptionRequest) (*HasSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserHasSubscription not implemented")
}
func (UnimplementedSubscriptionServer) UserClubComposer(context.Context, *SubscriptionRequest) (*Packet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserClubComposer not implemented")
}
func (UnimplementedSubscriptionServer) GetSessionSubscriptions(context.Context, *SessionSubscriptionRequest) (*Subscriptions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionSubscriptions not implemented")
}
func (UnimplementedSubscriptionServer) mustEmbedUnimplementedSubscriptionServer() {}
func (UnimplementedSubscriptionServer) testEmbeddedByValue()                      {}

// UnsafeSubscriptionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionServer will
// result in compilation errors.
type UnsafeSubscriptionServer interface {
	mustEmbedUnimplementedSubscriptionServer()
}

func RegisterSubscriptionServer(s grpc.ServiceRegistrar, srv SubscriptionServer) {
	// If the following call pancis, it indicates UnimplementedSubscriptionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Subscription_ServiceDesc, srv)
}

func _Subscription_GetSubscripitonsForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServer).GetSubscripitonsForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_GetSubscripitonsForUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServer).GetSubscripitonsForUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscription_AddDuration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServer).AddDuration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_AddDuration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServer).AddDuration(ctx, req.(*DurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscription_SetActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServer).SetActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_SetActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServer).SetActive(ctx, req.(*ActivationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscription_UserHasSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServer).UserHasSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_UserHasSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServer).UserHasSubscription(ctx, req.(*SubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscription_UserClubComposer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServer).UserClubComposer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_UserClubComposer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServer).UserClubComposer(ctx, req.(*SubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscription_GetSessionSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServer).GetSessionSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_GetSessionSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServer).GetSessionSubscriptions(ctx, req.(*SessionSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Subscription_ServiceDesc is the grpc.ServiceDesc for Subscription service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Subscription_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subscription.Subscription",
	HandlerType: (*SubscriptionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSubscripitonsForUser",
			Handler:    _Subscription_GetSubscripitonsForUser_Handler,
		},
		{
			MethodName: "AddDuration",
			Handler:    _Subscription_AddDuration_Handler,
		},
		{
			MethodName: "SetActive",
			Handler:    _Subscription_SetActive_Handler,
		},
		{
			MethodName: "UserHasSubscription",
			Handler:    _Subscription_UserHasSubscription_Handler,
		},
		{
			MethodName: "UserClubComposer",
			Handler:    _Subscription_UserClubComposer_Handler,
		},
		{
			MethodName: "GetSessionSubscriptions",
			Handler:    _Subscription_GetSessionSubscriptions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "subscription.proto",
}
