// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: subscription.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscriptionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SubscriptionType string                 `protobuf:"bytes,2,opt,name=subscription_type,json=subscriptionType,proto3" json:"subscription_type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubscriptionRequest) Reset() {
	*x = SubscriptionRequest{}
	mi := &file_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionRequest) ProtoMessage() {}

func (x *SubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *SubscriptionRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubscriptionRequest) GetSubscriptionType() string {
	if x != nil {
		return x.SubscriptionType
	}
	return ""
}

type HasSubscriptionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HasSubscription bool                   `protobuf:"varint,1,opt,name=has_subscription,json=hasSubscription,proto3" json:"has_subscription,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HasSubscriptionResponse) Reset() {
	*x = HasSubscriptionResponse{}
	mi := &file_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasSubscriptionResponse) ProtoMessage() {}

func (x *HasSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*HasSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *HasSubscriptionResponse) GetHasSubscription() bool {
	if x != nil {
		return x.HasSubscription
	}
	return false
}

type DurationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId int32                  `protobuf:"varint,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Duration       int32                  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DurationRequest) Reset() {
	*x = DurationRequest{}
	mi := &file_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationRequest) ProtoMessage() {}

func (x *DurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationRequest.ProtoReflect.Descriptor instead.
func (*DurationRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *DurationRequest) GetSubscriptionId() int32 {
	if x != nil {
		return x.SubscriptionId
	}
	return 0
}

func (x *DurationRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type ActivationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId int32                  `protobuf:"varint,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Active         bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActivationRequest) Reset() {
	*x = ActivationRequest{}
	mi := &file_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationRequest) ProtoMessage() {}

func (x *ActivationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationRequest.ProtoReflect.Descriptor instead.
func (*ActivationRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *ActivationRequest) GetSubscriptionId() int32 {
	if x != nil {
		return x.SubscriptionId
	}
	return 0
}

func (x *ActivationRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *Packet) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sso           *string                `protobuf:"bytes,2,opt,name=sso,proto3,oneof" json:"sso,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{5}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetSso() string {
	if x != nil && x.Sso != nil {
		return *x.Sso
	}
	return ""
}

type Subscriptions struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Subscriptions []*SubscriptionInstance `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscriptions) Reset() {
	*x = Subscriptions{}
	mi := &file_subscription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscriptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscriptions) ProtoMessage() {}

func (x *Subscriptions) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscriptions.ProtoReflect.Descriptor instead.
func (*Subscriptions) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{6}
}

func (x *Subscriptions) GetSubscriptions() []*SubscriptionInstance {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type SubscriptionInstance struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SubscriptionType string                 `protobuf:"bytes,3,opt,name=subscription_type,json=subscriptionType,proto3" json:"subscription_type,omitempty"`
	TimestampStart   int32                  `protobuf:"varint,4,opt,name=timestamp_start,json=timestampStart,proto3" json:"timestamp_start,omitempty"`
	Duration         int32                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	Active           bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubscriptionInstance) Reset() {
	*x = SubscriptionInstance{}
	mi := &file_subscription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionInstance) ProtoMessage() {}

func (x *SubscriptionInstance) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionInstance.ProtoReflect.Descriptor instead.
func (*SubscriptionInstance) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{7}
}

func (x *SubscriptionInstance) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubscriptionInstance) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubscriptionInstance) GetSubscriptionType() string {
	if x != nil {
		return x.SubscriptionType
	}
	return ""
}

func (x *SubscriptionInstance) GetTimestampStart() int32 {
	if x != nil {
		return x.TimestampStart
	}
	return 0
}

func (x *SubscriptionInstance) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *SubscriptionInstance) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

var File_subscription_proto protoreflect.FileDescriptor

const file_subscription_proto_rawDesc = "" +
	"\n" +
	"\x12subscription.proto\x12\fsubscription\"[\n" +
	"\x13SubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12+\n" +
	"\x11subscription_type\x18\x02 \x01(\tR\x10subscriptionType\"D\n" +
	"\x17HasSubscriptionResponse\x12)\n" +
	"\x10has_subscription\x18\x01 \x01(\bR\x0fhasSubscription\"V\n" +
	"\x0fDurationRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\x05R\x0esubscriptionId\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x05R\bduration\"T\n" +
	"\x11ActivationRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\x05R\x0esubscriptionId\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\"\x1c\n" +
	"\x06Packet\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"5\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x15\n" +
	"\x03sso\x18\x02 \x01(\tH\x00R\x03sso\x88\x01\x01B\x06\n" +
	"\x04_sso\"Y\n" +
	"\rSubscriptions\x12H\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\".subscription.SubscriptionInstanceR\rsubscriptions\"\xc9\x01\n" +
	"\x14SubscriptionInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12+\n" +
	"\x11subscription_type\x18\x03 \x01(\tR\x10subscriptionType\x12'\n" +
	"\x0ftimestamp_start\x18\x04 \x01(\x05R\x0etimestampStart\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x05R\bduration\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active2\xb6\x03\n" +
	"\fSubscription\x12L\n" +
	"\x17GetSubscripitonsForUser\x12\x12.subscription.User\x1a\x1b.subscription.Subscriptions\"\x00\x12R\n" +
	"\vAddDuration\x12\x1d.subscription.DurationRequest\x1a\".subscription.SubscriptionInstance\"\x00\x12R\n" +
	"\tSetActive\x12\x1f.subscription.ActivationRequest\x1a\".subscription.SubscriptionInstance\"\x00\x12a\n" +
	"\x13UserHasSubscription\x12!.subscription.SubscriptionRequest\x1a%.subscription.HasSubscriptionResponse\"\x00\x12M\n" +
	"\x10UserClubComposer\x12!.subscription.SubscriptionRequest\x1a\x14.subscription.Packet\"\x00B4Z2github.com/himalayo/clusterfuck/subscription/protob\x06proto3"

var (
	file_subscription_proto_rawDescOnce sync.Once
	file_subscription_proto_rawDescData []byte
)

func file_subscription_proto_rawDescGZIP() []byte {
	file_subscription_proto_rawDescOnce.Do(func() {
		file_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)))
	})
	return file_subscription_proto_rawDescData
}

var file_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_subscription_proto_goTypes = []any{
	(*SubscriptionRequest)(nil),     // 0: subscription.SubscriptionRequest
	(*HasSubscriptionResponse)(nil), // 1: subscription.HasSubscriptionResponse
	(*DurationRequest)(nil),         // 2: subscription.DurationRequest
	(*ActivationRequest)(nil),       // 3: subscription.ActivationRequest
	(*Packet)(nil),                  // 4: subscription.Packet
	(*User)(nil),                    // 5: subscription.User
	(*Subscriptions)(nil),           // 6: subscription.Subscriptions
	(*SubscriptionInstance)(nil),    // 7: subscription.SubscriptionInstance
}
var file_subscription_proto_depIdxs = []int32{
	7, // 0: subscription.Subscriptions.subscriptions:type_name -> subscription.SubscriptionInstance
	5, // 1: subscription.Subscription.GetSubscripitonsForUser:input_type -> subscription.User
	2, // 2: subscription.Subscription.AddDuration:input_type -> subscription.DurationRequest
	3, // 3: subscription.Subscription.SetActive:input_type -> subscription.ActivationRequest
	0, // 4: subscription.Subscription.UserHasSubscription:input_type -> subscription.SubscriptionRequest
	0, // 5: subscription.Subscription.UserClubComposer:input_type -> subscription.SubscriptionRequest
	6, // 6: subscription.Subscription.GetSubscripitonsForUser:output_type -> subscription.Subscriptions
	7, // 7: subscription.Subscription.AddDuration:output_type -> subscription.SubscriptionInstance
	7, // 8: subscription.Subscription.SetActive:output_type -> subscription.SubscriptionInstance
	1, // 9: subscription.Subscription.UserHasSubscription:output_type -> subscription.HasSubscriptionResponse
	4, // 10: subscription.Subscription.UserClubComposer:output_type -> subscription.Packet
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_subscription_proto_init() }
func file_subscription_proto_init() {
	if File_subscription_proto != nil {
		return
	}
	file_subscription_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subscription_proto_goTypes,
		DependencyIndexes: file_subscription_proto_depIdxs,
		MessageInfos:      file_subscription_proto_msgTypes,
	}.Build()
	File_subscription_proto = out.File
	file_subscription_proto_goTypes = nil
	file_subscription_proto_depIdxs = nil
}
