// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: modtool.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CfhActionType int32

const (
	CfhActionType_MODS        CfhActionType = 0
	CfhActionType_AUTO_REPLY  CfhActionType = 1
	CfhActionType_AUTO_IGNORE CfhActionType = 2
	CfhActionType_GUARDIANS   CfhActionType = 3
)

// Enum value maps for CfhActionType.
var (
	CfhActionType_name = map[int32]string{
		0: "MODS",
		1: "AUTO_REPLY",
		2: "AUTO_IGNORE",
		3: "GUARDIANS",
	}
	CfhActionType_value = map[string]int32{
		"MODS":        0,
		"AUTO_REPLY":  1,
		"AUTO_IGNORE": 2,
		"GUARDIANS":   3,
	}
)

func (x CfhActionType) Enum() *CfhActionType {
	p := new(CfhActionType)
	*p = x
	return p
}

func (x CfhActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CfhActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_modtool_proto_enumTypes[0].Descriptor()
}

func (CfhActionType) Type() protoreflect.EnumType {
	return &file_modtool_proto_enumTypes[0]
}

func (x CfhActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CfhActionType.Descriptor instead.
func (CfhActionType) EnumDescriptor() ([]byte, []int) {
	return file_modtool_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_modtool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_modtool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_modtool_proto_rawDescGZIP(), []int{0}
}

type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_modtool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_modtool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_modtool_proto_rawDescGZIP(), []int{1}
}

func (x *Packet) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TopicId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicId) Reset() {
	*x = TopicId{}
	mi := &file_modtool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicId) ProtoMessage() {}

func (x *TopicId) ProtoReflect() protoreflect.Message {
	mi := &file_modtool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicId.ProtoReflect.Descriptor instead.
func (*TopicId) Descriptor() ([]byte, []int) {
	return file_modtool_proto_rawDescGZIP(), []int{2}
}

func (x *TopicId) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type IssuePreset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Reminder      string                 `protobuf:"bytes,4,opt,name=reminder,proto3" json:"reminder,omitempty"`
	BanLength     int32                  `protobuf:"varint,5,opt,name=ban_length,json=banLength,proto3" json:"ban_length,omitempty"`
	MuteLength    int32                  `protobuf:"varint,6,opt,name=mute_length,json=muteLength,proto3" json:"mute_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuePreset) Reset() {
	*x = IssuePreset{}
	mi := &file_modtool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuePreset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuePreset) ProtoMessage() {}

func (x *IssuePreset) ProtoReflect() protoreflect.Message {
	mi := &file_modtool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuePreset.ProtoReflect.Descriptor instead.
func (*IssuePreset) Descriptor() ([]byte, []int) {
	return file_modtool_proto_rawDescGZIP(), []int{3}
}

func (x *IssuePreset) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IssuePreset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IssuePreset) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IssuePreset) GetReminder() string {
	if x != nil {
		return x.Reminder
	}
	return ""
}

func (x *IssuePreset) GetBanLength() int32 {
	if x != nil {
		return x.BanLength
	}
	return 0
}

func (x *IssuePreset) GetMuteLength() int32 {
	if x != nil {
		return x.MuteLength
	}
	return 0
}

type CfhTopic struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Action          CfhActionType          `protobuf:"varint,3,opt,name=action,proto3,enum=modtool.CfhActionType" json:"action,omitempty"`
	IgnoreTarget    bool                   `protobuf:"varint,4,opt,name=ignore_target,json=ignoreTarget,proto3" json:"ignore_target,omitempty"`
	Reply           string                 `protobuf:"bytes,5,opt,name=reply,proto3" json:"reply,omitempty"`
	DefaultSanction *IssuePreset           `protobuf:"bytes,6,opt,name=default_sanction,json=defaultSanction,proto3" json:"default_sanction,omitempty"`
	NameExternal    string                 `protobuf:"bytes,7,opt,name=name_external,json=nameExternal,proto3" json:"name_external,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CfhTopic) Reset() {
	*x = CfhTopic{}
	mi := &file_modtool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CfhTopic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CfhTopic) ProtoMessage() {}

func (x *CfhTopic) ProtoReflect() protoreflect.Message {
	mi := &file_modtool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CfhTopic.ProtoReflect.Descriptor instead.
func (*CfhTopic) Descriptor() ([]byte, []int) {
	return file_modtool_proto_rawDescGZIP(), []int{4}
}

func (x *CfhTopic) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CfhTopic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CfhTopic) GetAction() CfhActionType {
	if x != nil {
		return x.Action
	}
	return CfhActionType_MODS
}

func (x *CfhTopic) GetIgnoreTarget() bool {
	if x != nil {
		return x.IgnoreTarget
	}
	return false
}

func (x *CfhTopic) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *CfhTopic) GetDefaultSanction() *IssuePreset {
	if x != nil {
		return x.DefaultSanction
	}
	return nil
}

func (x *CfhTopic) GetNameExternal() string {
	if x != nil {
		return x.NameExternal
	}
	return ""
}

var File_modtool_proto protoreflect.FileDescriptor

const file_modtool_proto_rawDesc = "" +
	"\n" +
	"\rmodtool.proto\x12\amodtool\"\a\n" +
	"\x05Empty\"\x1c\n" +
	"\x06Packet\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x19\n" +
	"\aTopicId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xa7\x01\n" +
	"\vIssuePreset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1a\n" +
	"\breminder\x18\x04 \x01(\tR\breminder\x12\x1d\n" +
	"\n" +
	"ban_length\x18\x05 \x01(\x05R\tbanLength\x12\x1f\n" +
	"\vmute_length\x18\x06 \x01(\x05R\n" +
	"muteLength\"\xff\x01\n" +
	"\bCfhTopic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\x06action\x18\x03 \x01(\x0e2\x16.modtool.CfhActionTypeR\x06action\x12#\n" +
	"\rignore_target\x18\x04 \x01(\bR\fignoreTarget\x12\x14\n" +
	"\x05reply\x18\x05 \x01(\tR\x05reply\x12?\n" +
	"\x10default_sanction\x18\x06 \x01(\v2\x14.modtool.IssuePresetR\x0fdefaultSanction\x12#\n" +
	"\rname_external\x18\a \x01(\tR\fnameExternal*I\n" +
	"\rCfhActionType\x12\b\n" +
	"\x04MODS\x10\x00\x12\x0e\n" +
	"\n" +
	"AUTO_REPLY\x10\x01\x12\x0f\n" +
	"\vAUTO_IGNORE\x10\x02\x12\r\n" +
	"\tGUARDIANS\x10\x032~\n" +
	"\aModtool\x124\n" +
	"\vGetCfhTopic\x12\x10.modtool.TopicId\x1a\x11.modtool.CfhTopic\"\x00\x12=\n" +
	"\x18CfhTopicsMessageComposer\x12\x0e.modtool.Empty\x1a\x0f.modtool.Packet\"\x00B/Z-github.com/himalayo/clusterfuck/modtool/protob\x06proto3"

var (
	file_modtool_proto_rawDescOnce sync.Once
	file_modtool_proto_rawDescData []byte
)

func file_modtool_proto_rawDescGZIP() []byte {
	file_modtool_proto_rawDescOnce.Do(func() {
		file_modtool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modtool_proto_rawDesc), len(file_modtool_proto_rawDesc)))
	})
	return file_modtool_proto_rawDescData
}

var file_modtool_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_modtool_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_modtool_proto_goTypes = []any{
	(CfhActionType)(0),  // 0: modtool.CfhActionType
	(*Empty)(nil),       // 1: modtool.Empty
	(*Packet)(nil),      // 2: modtool.Packet
	(*TopicId)(nil),     // 3: modtool.TopicId
	(*IssuePreset)(nil), // 4: modtool.IssuePreset
	(*CfhTopic)(nil),    // 5: modtool.CfhTopic
}
var file_modtool_proto_depIdxs = []int32{
	0, // 0: modtool.CfhTopic.action:type_name -> modtool.CfhActionType
	4, // 1: modtool.CfhTopic.default_sanction:type_name -> modtool.IssuePreset
	3, // 2: modtool.Modtool.GetCfhTopic:input_type -> modtool.TopicId
	1, // 3: modtool.Modtool.CfhTopicsMessageComposer:input_type -> modtool.Empty
	5, // 4: modtool.Modtool.GetCfhTopic:output_type -> modtool.CfhTopic
	2, // 5: modtool.Modtool.CfhTopicsMessageComposer:output_type -> modtool.Packet
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_modtool_proto_init() }
func file_modtool_proto_init() {
	if File_modtool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modtool_proto_rawDesc), len(file_modtool_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modtool_proto_goTypes,
		DependencyIndexes: file_modtool_proto_depIdxs,
		EnumInfos:         file_modtool_proto_enumTypes,
		MessageInfos:      file_modtool_proto_msgTypes,
	}.Build()
	File_modtool_proto = out.File
	file_modtool_proto_goTypes = nil
	file_modtool_proto_depIdxs = nil
}
