syntax = "proto3";

package networking;

option go_package = "github.com/himalayo/clusterfuck/networking/proto";

service Networking {
	rpc SendPacket (Packet) returns (SuccessMessage) {}
	rpc SendPackets (Packets) returns (SuccessMessage) {}
	rpc RegisterIncomingListener (IncomingInstance) returns (SuccessMessage) {}
	rpc DisconnectIncomingListener (IncomingInstance) returns (SuccessMessage) {}
	rpc RegisterRedisListener (RedisListener) returns (SuccessMessage) {}
}

service IncomingListener {
	rpc ReceivePacket (Packet) returns (SuccessMessage) {}
}

message IncomingInstance {
	string address = 1;
	repeated int32 headers = 2;
	string application = 3;
}

message RedisInstance {
	string address = 1;
	string password = 2;
	int32 db = 3;
}

message RedisListener {
	RedisInstance redis = 1;
	string stream = 2;
	string group = 3;
	repeated int32 headers = 4;	
}

message PacketEvent {
	string id = 1;
	string type = 2;
	Packet packet = 3;
}

message Packets {
	string client_id = 1;
	repeated bytes packets = 2;
}

message Packet {
	string client_id = 1;
	bytes packet = 2;
}

message SuccessMessage {
	bool successful = 1;
	string message = 2;	
}
