// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: networking.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IncomingInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Headers       []int32                `protobuf:"varint,2,rep,packed,name=headers,proto3" json:"headers,omitempty"`
	Application   string                 `protobuf:"bytes,3,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomingInstance) Reset() {
	*x = IncomingInstance{}
	mi := &file_networking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingInstance) ProtoMessage() {}

func (x *IncomingInstance) ProtoReflect() protoreflect.Message {
	mi := &file_networking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingInstance.ProtoReflect.Descriptor instead.
func (*IncomingInstance) Descriptor() ([]byte, []int) {
	return file_networking_proto_rawDescGZIP(), []int{0}
}

func (x *IncomingInstance) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *IncomingInstance) GetHeaders() []int32 {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *IncomingInstance) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

type Packets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Packets       [][]byte               `protobuf:"bytes,2,rep,name=packets,proto3" json:"packets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packets) Reset() {
	*x = Packets{}
	mi := &file_networking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packets) ProtoMessage() {}

func (x *Packets) ProtoReflect() protoreflect.Message {
	mi := &file_networking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packets.ProtoReflect.Descriptor instead.
func (*Packets) Descriptor() ([]byte, []int) {
	return file_networking_proto_rawDescGZIP(), []int{1}
}

func (x *Packets) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Packets) GetPackets() [][]byte {
	if x != nil {
		return x.Packets
	}
	return nil
}

type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Packet        []byte                 `protobuf:"bytes,2,opt,name=packet,proto3" json:"packet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_networking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_networking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_networking_proto_rawDescGZIP(), []int{2}
}

func (x *Packet) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Packet) GetPacket() []byte {
	if x != nil {
		return x.Packet
	}
	return nil
}

type SuccessMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Successful    bool                   `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessMessage) Reset() {
	*x = SuccessMessage{}
	mi := &file_networking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessMessage) ProtoMessage() {}

func (x *SuccessMessage) ProtoReflect() protoreflect.Message {
	mi := &file_networking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessMessage.ProtoReflect.Descriptor instead.
func (*SuccessMessage) Descriptor() ([]byte, []int) {
	return file_networking_proto_rawDescGZIP(), []int{3}
}

func (x *SuccessMessage) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *SuccessMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_networking_proto protoreflect.FileDescriptor

const file_networking_proto_rawDesc = "" +
	"\n" +
	"\x10networking.proto\x12\n" +
	"networking\"h\n" +
	"\x10IncomingInstance\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x18\n" +
	"\aheaders\x18\x02 \x03(\x05R\aheaders\x12 \n" +
	"\vapplication\x18\x03 \x01(\tR\vapplication\"@\n" +
	"\aPackets\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x18\n" +
	"\apackets\x18\x02 \x03(\fR\apackets\"=\n" +
	"\x06Packet\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x16\n" +
	"\x06packet\x18\x02 \x01(\fR\x06packet\"J\n" +
	"\x0eSuccessMessage\x12\x1e\n" +
	"\n" +
	"successful\x18\x01 \x01(\bR\n" +
	"successful\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xc0\x02\n" +
	"\n" +
	"Networking\x12>\n" +
	"\n" +
	"SendPacket\x12\x12.networking.Packet\x1a\x1a.networking.SuccessMessage\"\x00\x12@\n" +
	"\vSendPackets\x12\x13.networking.Packets\x1a\x1a.networking.SuccessMessage\"\x00\x12V\n" +
	"\x18RegisterIncomingListener\x12\x1c.networking.IncomingInstance\x1a\x1a.networking.SuccessMessage\"\x00\x12X\n" +
	"\x1aDisconnectIncomingListener\x12\x1c.networking.IncomingInstance\x1a\x1a.networking.SuccessMessage\"\x002U\n" +
	"\x10IncomingListener\x12A\n" +
	"\rReceivePacket\x12\x12.networking.Packet\x1a\x1a.networking.SuccessMessage\"\x00B2Z0github.com/himalayo/clusterfuck/networking/protob\x06proto3"

var (
	file_networking_proto_rawDescOnce sync.Once
	file_networking_proto_rawDescData []byte
)

func file_networking_proto_rawDescGZIP() []byte {
	file_networking_proto_rawDescOnce.Do(func() {
		file_networking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_networking_proto_rawDesc), len(file_networking_proto_rawDesc)))
	})
	return file_networking_proto_rawDescData
}

var file_networking_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_networking_proto_goTypes = []any{
	(*IncomingInstance)(nil), // 0: networking.IncomingInstance
	(*Packets)(nil),          // 1: networking.Packets
	(*Packet)(nil),           // 2: networking.Packet
	(*SuccessMessage)(nil),   // 3: networking.SuccessMessage
}
var file_networking_proto_depIdxs = []int32{
	2, // 0: networking.Networking.SendPacket:input_type -> networking.Packet
	1, // 1: networking.Networking.SendPackets:input_type -> networking.Packets
	0, // 2: networking.Networking.RegisterIncomingListener:input_type -> networking.IncomingInstance
	0, // 3: networking.Networking.DisconnectIncomingListener:input_type -> networking.IncomingInstance
	2, // 4: networking.IncomingListener.ReceivePacket:input_type -> networking.Packet
	3, // 5: networking.Networking.SendPacket:output_type -> networking.SuccessMessage
	3, // 6: networking.Networking.SendPackets:output_type -> networking.SuccessMessage
	3, // 7: networking.Networking.RegisterIncomingListener:output_type -> networking.SuccessMessage
	3, // 8: networking.Networking.DisconnectIncomingListener:output_type -> networking.SuccessMessage
	3, // 9: networking.IncomingListener.ReceivePacket:output_type -> networking.SuccessMessage
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_networking_proto_init() }
func file_networking_proto_init() {
	if File_networking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_networking_proto_rawDesc), len(file_networking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_networking_proto_goTypes,
		DependencyIndexes: file_networking_proto_depIdxs,
		MessageInfos:      file_networking_proto_msgTypes,
	}.Build()
	File_networking_proto = out.File
	file_networking_proto_goTypes = nil
	file_networking_proto_depIdxs = nil
}
