// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: networking.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Networking_SendPacket_FullMethodName                 = "/networking.Networking/SendPacket"
	Networking_SendPackets_FullMethodName                = "/networking.Networking/SendPackets"
	Networking_RegisterIncomingListener_FullMethodName   = "/networking.Networking/RegisterIncomingListener"
	Networking_DisconnectIncomingListener_FullMethodName = "/networking.Networking/DisconnectIncomingListener"
)

// NetworkingClient is the client API for Networking service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetworkingClient interface {
	SendPacket(ctx context.Context, in *Packet, opts ...grpc.CallOption) (*SuccessMessage, error)
	SendPackets(ctx context.Context, in *Packets, opts ...grpc.CallOption) (*SuccessMessage, error)
	RegisterIncomingListener(ctx context.Context, in *IncomingInstance, opts ...grpc.CallOption) (*SuccessMessage, error)
	DisconnectIncomingListener(ctx context.Context, in *IncomingInstance, opts ...grpc.CallOption) (*SuccessMessage, error)
}

type networkingClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkingClient(cc grpc.ClientConnInterface) NetworkingClient {
	return &networkingClient{cc}
}

func (c *networkingClient) SendPacket(ctx context.Context, in *Packet, opts ...grpc.CallOption) (*SuccessMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessMessage)
	err := c.cc.Invoke(ctx, Networking_SendPacket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkingClient) SendPackets(ctx context.Context, in *Packets, opts ...grpc.CallOption) (*SuccessMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessMessage)
	err := c.cc.Invoke(ctx, Networking_SendPackets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkingClient) RegisterIncomingListener(ctx context.Context, in *IncomingInstance, opts ...grpc.CallOption) (*SuccessMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessMessage)
	err := c.cc.Invoke(ctx, Networking_RegisterIncomingListener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkingClient) DisconnectIncomingListener(ctx context.Context, in *IncomingInstance, opts ...grpc.CallOption) (*SuccessMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessMessage)
	err := c.cc.Invoke(ctx, Networking_DisconnectIncomingListener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkingServer is the server API for Networking service.
// All implementations must embed UnimplementedNetworkingServer
// for forward compatibility.
type NetworkingServer interface {
	SendPacket(context.Context, *Packet) (*SuccessMessage, error)
	SendPackets(context.Context, *Packets) (*SuccessMessage, error)
	RegisterIncomingListener(context.Context, *IncomingInstance) (*SuccessMessage, error)
	DisconnectIncomingListener(context.Context, *IncomingInstance) (*SuccessMessage, error)
	mustEmbedUnimplementedNetworkingServer()
}

// UnimplementedNetworkingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkingServer struct{}

func (UnimplementedNetworkingServer) SendPacket(context.Context, *Packet) (*SuccessMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPacket not implemented")
}
func (UnimplementedNetworkingServer) SendPackets(context.Context, *Packets) (*SuccessMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPackets not implemented")
}
func (UnimplementedNetworkingServer) RegisterIncomingListener(context.Context, *IncomingInstance) (*SuccessMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterIncomingListener not implemented")
}
func (UnimplementedNetworkingServer) DisconnectIncomingListener(context.Context, *IncomingInstance) (*SuccessMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisconnectIncomingListener not implemented")
}
func (UnimplementedNetworkingServer) mustEmbedUnimplementedNetworkingServer() {}
func (UnimplementedNetworkingServer) testEmbeddedByValue()                    {}

// UnsafeNetworkingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkingServer will
// result in compilation errors.
type UnsafeNetworkingServer interface {
	mustEmbedUnimplementedNetworkingServer()
}

func RegisterNetworkingServer(s grpc.ServiceRegistrar, srv NetworkingServer) {
	// If the following call pancis, it indicates UnimplementedNetworkingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Networking_ServiceDesc, srv)
}

func _Networking_SendPacket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Packet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkingServer).SendPacket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Networking_SendPacket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkingServer).SendPacket(ctx, req.(*Packet))
	}
	return interceptor(ctx, in, info, handler)
}

func _Networking_SendPackets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Packets)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkingServer).SendPackets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Networking_SendPackets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkingServer).SendPackets(ctx, req.(*Packets))
	}
	return interceptor(ctx, in, info, handler)
}

func _Networking_RegisterIncomingListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncomingInstance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkingServer).RegisterIncomingListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Networking_RegisterIncomingListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkingServer).RegisterIncomingListener(ctx, req.(*IncomingInstance))
	}
	return interceptor(ctx, in, info, handler)
}

func _Networking_DisconnectIncomingListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncomingInstance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkingServer).DisconnectIncomingListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Networking_DisconnectIncomingListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkingServer).DisconnectIncomingListener(ctx, req.(*IncomingInstance))
	}
	return interceptor(ctx, in, info, handler)
}

// Networking_ServiceDesc is the grpc.ServiceDesc for Networking service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Networking_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "networking.Networking",
	HandlerType: (*NetworkingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPacket",
			Handler:    _Networking_SendPacket_Handler,
		},
		{
			MethodName: "SendPackets",
			Handler:    _Networking_SendPackets_Handler,
		},
		{
			MethodName: "RegisterIncomingListener",
			Handler:    _Networking_RegisterIncomingListener_Handler,
		},
		{
			MethodName: "DisconnectIncomingListener",
			Handler:    _Networking_DisconnectIncomingListener_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "networking.proto",
}

const (
	IncomingListener_ReceivePacket_FullMethodName = "/networking.IncomingListener/ReceivePacket"
)

// IncomingListenerClient is the client API for IncomingListener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IncomingListenerClient interface {
	ReceivePacket(ctx context.Context, in *Packet, opts ...grpc.CallOption) (*SuccessMessage, error)
}

type incomingListenerClient struct {
	cc grpc.ClientConnInterface
}

func NewIncomingListenerClient(cc grpc.ClientConnInterface) IncomingListenerClient {
	return &incomingListenerClient{cc}
}

func (c *incomingListenerClient) ReceivePacket(ctx context.Context, in *Packet, opts ...grpc.CallOption) (*SuccessMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessMessage)
	err := c.cc.Invoke(ctx, IncomingListener_ReceivePacket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IncomingListenerServer is the server API for IncomingListener service.
// All implementations must embed UnimplementedIncomingListenerServer
// for forward compatibility.
type IncomingListenerServer interface {
	ReceivePacket(context.Context, *Packet) (*SuccessMessage, error)
	mustEmbedUnimplementedIncomingListenerServer()
}

// UnimplementedIncomingListenerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIncomingListenerServer struct{}

func (UnimplementedIncomingListenerServer) ReceivePacket(context.Context, *Packet) (*SuccessMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceivePacket not implemented")
}
func (UnimplementedIncomingListenerServer) mustEmbedUnimplementedIncomingListenerServer() {}
func (UnimplementedIncomingListenerServer) testEmbeddedByValue()                          {}

// UnsafeIncomingListenerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IncomingListenerServer will
// result in compilation errors.
type UnsafeIncomingListenerServer interface {
	mustEmbedUnimplementedIncomingListenerServer()
}

func RegisterIncomingListenerServer(s grpc.ServiceRegistrar, srv IncomingListenerServer) {
	// If the following call pancis, it indicates UnimplementedIncomingListenerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IncomingListener_ServiceDesc, srv)
}

func _IncomingListener_ReceivePacket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Packet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncomingListenerServer).ReceivePacket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IncomingListener_ReceivePacket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncomingListenerServer).ReceivePacket(ctx, req.(*Packet))
	}
	return interceptor(ctx, in, info, handler)
}

// IncomingListener_ServiceDesc is the grpc.ServiceDesc for IncomingListener service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IncomingListener_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "networking.IncomingListener",
	HandlerType: (*IncomingListenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceivePacket",
			Handler:    _IncomingListener_ReceivePacket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "networking.proto",
}
