services:
  mariadb:
    env_file: docker.env
    container_name: mariadb
    hostname: mariadb
    image: 'mariadb:10'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASS}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
        - '3306:3306'
    volumes:
      - 'mariadb_data:/var/lib/mysql'
      - './default-database:/docker-entrypoint-initdb.d'
    networks:
      - clusterfuck_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASS}" ]
      retries: 3
      timeout: 5s
  
  networking:
    env_file: docker.env
    container_name: networking
    hostname: networking
    ports:
      - '2096:2096'
    build:
      context: ./
      dockerfile: ./networking/Dockerfile
    restart: always
    depends_on:
      configuration:
        condition: service_started
      player-event-redis:
        condition: service_healthy
    networks:
      - clusterfuck_network

  player:
    env_file: docker.env
    container_name: player
    hostname: player
    build:
      context: ./
      dockerfile: ./player/Dockerfile
    restart: always
    networks:
      - clusterfuck_network
    depends_on:
      networking:
        condition: service_started
      achievements:
        condition: service_started
      configuration:
        condition: service_started
      modtool:
        condition: service_started
      permission:
        condition: service_started
      subscription:
        condition: service_started
      mariadb:
        condition: service_healthy
  
  achievements:
    env_file: docker.env
    container_name: achievements
    hostname: achievements
    build:
      context: ./
      dockerfile: ./achievements/Dockerfile
    restart: always
    networks:
      - clusterfuck_network
    depends_on:
      networking:
        condition: service_started
      mariadb:
        condition: service_healthy

  configuration:
    env_file: docker.env
    container_name: configuration 
    hostname: configuration
    build:
      context: ./
      dockerfile: ./configuration/Dockerfile
    restart: always
    networks:
      - clusterfuck_network
    depends_on:
      mariadb:
        condition: service_healthy
  
  catalog:
    env_file: docker.env
    container_name: catalog
    hostname: catalog
    build:
      context: ./
      dockerfile: ./catalog/Dockerfile
    restart: always
    networks:
      - clusterfuck_network
    depends_on:
      networking:
        condition: service_started
      items:
        condition: service_started
      mariadb:
        condition: service_healthy

  guilds:
    env_file: docker.env
    container_name: guilds
    hostname: guilds
    build:
      context: ./
      dockerfile: ./guilds/Dockerfile
    restart: always
    networks:
      - clusterfuck_network
    depends_on:
      networking:
        condition: service_started
      mariadb:
        condition: service_healthy

  items:
    env_file: docker.env
    container_name: items
    hostname: items
    build:
      context: ./
      dockerfile: ./items/Dockerfile
    restart: always
    networks:
      - clusterfuck_network
    depends_on:
      mariadb:
        condition: service_healthy

  modtool:
    env_file: docker.env
    container_name: modtool
    hostname: modtool
    build:
      context: ./
      dockerfile: ./modtool/Dockerfile
    restart: always
    networks:
      - clusterfuck_network
    depends_on:
      mariadb:
        condition: service_healthy
    
  permission:
    env_file: docker.env
    container_name: permission
    hostname: permission
    build:
      context: ./
      dockerfile: ./permission/Dockerfile
    restart: always
    networks:
      - clusterfuck_network
    depends_on:
      networking:
        condition: service_started
      mariadb:
        condition: service_healthy

  subscription:
    env_file: docker.env
    container_name: subscription
    hostname: subscription
    build:
      context: ./
      dockerfile: ./subscription/Dockerfile
    restart: always
    networks:
      - clusterfuck_network
    depends_on:
      networking:
        condition: service_started
      mariadb:
        condition: service_healthy

  guilds-redis:
    image: 'redis:alpine'
    hostname: guilds-redis
    container_name: guilds-redis
    volumes:
        - 'guilds_redis:/data'
    networks:
        - clusterfuck_network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s

  guilds-outgoing-redis:
    image: 'redis:alpine'
    hostname: guilds-outgoing-redis
    container_name: guilds-outgoing-redis
    volumes:
        - 'guilds_outgoing_redis:/data'
    networks:
        - clusterfuck_network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s

  guilds-event-redis:
    image: 'redis:alpine'
    hostname: guilds-event-redis
    container_name: guilds-event-redis
    volumes:
        - 'guilds_event_redis:/data'
    networks:
        - clusterfuck_network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s

  items-redis:
    image: 'redis:alpine'
    hostname: items-redis
    container_name: items-redis
    volumes:
        - 'items_redis:/data'
    networks:
        - clusterfuck_network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s

  permission-redis:
    image: 'redis:alpine'
    hostname: permission-redis
    container_name: permission-redis
    volumes:
        - 'permission_redis:/data'
    networks:
        - clusterfuck_network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s

  permission-outgoing-redis:
    image: 'redis:alpine'
    hostname: permission-outgoing-redis
    container_name: permission-outgoing-redis
    volumes:
        - 'permission_outgoing_redis:/data'
    networks:
        - clusterfuck_network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s

  permission-event-redis:
    image: 'redis:alpine'
    hostname: permission-event-redis
    container_name: permission-event-redis
    volumes:
        - 'permission_event_redis:/data'
    networks:
        - clusterfuck_network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s

  achievements-redis:
    image: 'redis:alpine'
    hostname: achievements-redis
    container_name: achievements-redis
    volumes:
        - 'achievements_redis:/data'
    networks:
        - clusterfuck_network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s

  achievements-outgoing-redis:
    image: 'redis:alpine'
    hostname: achievements-outgoing-redis
    container_name: achievements-outgoing-redis
    volumes:
        - 'achievements_outgoing_redis:/data'
    networks:
        - clusterfuck_network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s

  achievements-event-redis:
    image: 'redis:alpine'
    hostname: achievements-event-redis
    container_name: achievements-event-redis
    volumes:
        - 'achievements_event_redis:/data'
    networks:
        - clusterfuck_network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s

  catalog-redis:
    image: 'redis:alpine'
    hostname: catalog-redis
    container_name: catalog-redis
    volumes:
        - 'catalog_redis:/data'
    networks:
        - clusterfuck_network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s

  catalog-outgoing-redis:
    image: 'redis:alpine'
    hostname: catalog-outgoing-redis
    container_name: catalog-outgoing-redis
    volumes:
        - 'catalog_outgoing_redis:/data'
    networks:
        - clusterfuck_network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s

  catalog-event-redis:
    image: 'redis:alpine'
    hostname: catalog-event-redis
    container_name: catalog-event-redis
    volumes:
        - 'catalog_event_redis:/data'
    networks:
        - clusterfuck_network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s

  player-outgoing-redis:
    image: 'redis:alpine'
    hostname: player-outgoing-redis
    container_name: player-outgoing-redis
    volumes:
        - 'player_outgoing_redis:/data'
    networks:
        - clusterfuck_network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s

  player-event-redis:
    image: 'redis:alpine'
    hostname: player-event-redis
    container_name: player-event-redis
    volumes:
        - 'player_event_redis:/data'
    networks:
        - clusterfuck_network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s

  player-redis:
    image: 'redis:alpine'
    hostname: player-redis
    container_name: player-redis
    ports:
        - '${PLAYER_REDIS_PORT:-6379}:6379'
    volumes:
        - 'player_redis:/data'
    networks:
        - clusterfuck_network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s
    
  configuration-redis:
    image: 'redis:alpine'
    hostname: configuration-redis
    container_name: configuration-redis
    volumes:
        - 'configuration_redis:/data'
    networks:
        - clusterfuck_network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s

  configuration-event-redis:
    image: 'redis:alpine'
    hostname: configuration-event-redis
    container_name: configuration-event-redis
    volumes:
        - 'configuration_event_redis:/data'
    networks:
        - clusterfuck_network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s

  subscription-redis:
    image: 'redis:alpine'
    hostname: subscription-redis
    container_name: subscription-redis
    volumes:
        - 'subscription_redis:/data'
    networks:
        - clusterfuck_network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s

  subscription-outgoing-redis:
    image: 'redis:alpine'
    hostname: subscription-outgoing-redis
    container_name: subscription-outgoing-redis
    volumes:
        - 'subscription_outgoing_redis:/data'
    networks:
        - clusterfuck_network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s

  subscription-event-redis:
    image: 'redis:alpine'
    hostname: subscription-event-redis
    container_name: subscription-event-redis
    volumes:
        - 'subscription_event_redis:/data'
    networks:
        - clusterfuck_network
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s

networks:
  clusterfuck_network:
    driver: bridge


volumes:
  achievements_outgoing_redis:
    driver: local
  achievements_event_redis:
    driver: local
  achievements_redis:
    driver: local
  catalog_outgoing_redis:
    driver: local
  catalog_event_redis:
    driver: local
  catalog_redis:
    driver: local
  configuration_redis:
    driver: local
  configuration_event_redis:
    driver: local
  guilds_redis:
    driver: local
  guilds_outgoing_redis:
    driver: local
  guilds_event_redis:
    driver: local
  items_redis:
    driver: local
  permission_redis:
    driver: local
  permission_outgoing_redis:
    driver: local
  permission_event_redis:
    driver: local
  player_redis:
    driver: local
  player_outgoing_redis:
    driver: local
  player_event_redis:
    driver: local
  subscription_redis:
    driver: local
  subscription_outgoing_redis:
    driver: local
  subscription_event_redis:
    driver: local
  mariadb_data:
    driver: local