// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: configuration.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigurationResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ConfigurationResult_BooleanConfig
	//	*ConfigurationResult_IntConfig
	//	*ConfigurationResult_DoubleConfig
	//	*ConfigurationResult_StringConfig
	Value         isConfigurationResult_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationResult) Reset() {
	*x = ConfigurationResult{}
	mi := &file_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationResult) ProtoMessage() {}

func (x *ConfigurationResult) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationResult.ProtoReflect.Descriptor instead.
func (*ConfigurationResult) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigurationResult) GetValue() isConfigurationResult_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ConfigurationResult) GetBooleanConfig() *BooleanConfiguration {
	if x != nil {
		if x, ok := x.Value.(*ConfigurationResult_BooleanConfig); ok {
			return x.BooleanConfig
		}
	}
	return nil
}

func (x *ConfigurationResult) GetIntConfig() *IntConfiguration {
	if x != nil {
		if x, ok := x.Value.(*ConfigurationResult_IntConfig); ok {
			return x.IntConfig
		}
	}
	return nil
}

func (x *ConfigurationResult) GetDoubleConfig() *DoubleConfiguration {
	if x != nil {
		if x, ok := x.Value.(*ConfigurationResult_DoubleConfig); ok {
			return x.DoubleConfig
		}
	}
	return nil
}

func (x *ConfigurationResult) GetStringConfig() *StringConfiguration {
	if x != nil {
		if x, ok := x.Value.(*ConfigurationResult_StringConfig); ok {
			return x.StringConfig
		}
	}
	return nil
}

type isConfigurationResult_Value interface {
	isConfigurationResult_Value()
}

type ConfigurationResult_BooleanConfig struct {
	BooleanConfig *BooleanConfiguration `protobuf:"bytes,1,opt,name=boolean_config,json=booleanConfig,proto3,oneof"`
}

type ConfigurationResult_IntConfig struct {
	IntConfig *IntConfiguration `protobuf:"bytes,2,opt,name=int_config,json=intConfig,proto3,oneof"`
}

type ConfigurationResult_DoubleConfig struct {
	DoubleConfig *DoubleConfiguration `protobuf:"bytes,3,opt,name=double_config,json=doubleConfig,proto3,oneof"`
}

type ConfigurationResult_StringConfig struct {
	StringConfig *StringConfiguration `protobuf:"bytes,4,opt,name=string_config,json=stringConfig,proto3,oneof"`
}

func (*ConfigurationResult_BooleanConfig) isConfigurationResult_Value() {}

func (*ConfigurationResult_IntConfig) isConfigurationResult_Value() {}

func (*ConfigurationResult_DoubleConfig) isConfigurationResult_Value() {}

func (*ConfigurationResult_StringConfig) isConfigurationResult_Value() {}

type BooleanConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        bool                   `protobuf:"varint,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooleanConfiguration) Reset() {
	*x = BooleanConfiguration{}
	mi := &file_configuration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooleanConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanConfiguration) ProtoMessage() {}

func (x *BooleanConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanConfiguration.ProtoReflect.Descriptor instead.
func (*BooleanConfiguration) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{1}
}

func (x *BooleanConfiguration) GetConfig() bool {
	if x != nil {
		return x.Config
	}
	return false
}

type IntConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        int32                  `protobuf:"varint,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntConfiguration) Reset() {
	*x = IntConfiguration{}
	mi := &file_configuration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntConfiguration) ProtoMessage() {}

func (x *IntConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntConfiguration.ProtoReflect.Descriptor instead.
func (*IntConfiguration) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{2}
}

func (x *IntConfiguration) GetConfig() int32 {
	if x != nil {
		return x.Config
	}
	return 0
}

type DoubleConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        float64                `protobuf:"fixed64,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoubleConfiguration) Reset() {
	*x = DoubleConfiguration{}
	mi := &file_configuration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoubleConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleConfiguration) ProtoMessage() {}

func (x *DoubleConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleConfiguration.ProtoReflect.Descriptor instead.
func (*DoubleConfiguration) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{3}
}

func (x *DoubleConfiguration) GetConfig() float64 {
	if x != nil {
		return x.Config
	}
	return 0
}

type StringConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringConfiguration) Reset() {
	*x = StringConfiguration{}
	mi := &file_configuration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringConfiguration) ProtoMessage() {}

func (x *StringConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringConfiguration.ProtoReflect.Descriptor instead.
func (*StringConfiguration) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{4}
}

func (x *StringConfiguration) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type ConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	DefaultResult *ConfigurationResult   `protobuf:"bytes,2,opt,name=default_result,json=defaultResult,proto3,oneof" json:"default_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationRequest) Reset() {
	*x = ConfigurationRequest{}
	mi := &file_configuration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationRequest) ProtoMessage() {}

func (x *ConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationRequest.ProtoReflect.Descriptor instead.
func (*ConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigurationRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigurationRequest) GetDefaultResult() *ConfigurationResult {
	if x != nil {
		return x.DefaultResult
	}
	return nil
}

var File_configuration_proto protoreflect.FileDescriptor

const file_configuration_proto_rawDesc = "" +
	"\n" +
	"\x13configuration.proto\x12\rconfiguration\"\xc4\x02\n" +
	"\x13ConfigurationResult\x12L\n" +
	"\x0eboolean_config\x18\x01 \x01(\v2#.configuration.BooleanConfigurationH\x00R\rbooleanConfig\x12@\n" +
	"\n" +
	"int_config\x18\x02 \x01(\v2\x1f.configuration.IntConfigurationH\x00R\tintConfig\x12I\n" +
	"\rdouble_config\x18\x03 \x01(\v2\".configuration.DoubleConfigurationH\x00R\fdoubleConfig\x12I\n" +
	"\rstring_config\x18\x04 \x01(\v2\".configuration.StringConfigurationH\x00R\fstringConfigB\a\n" +
	"\x05value\".\n" +
	"\x14BooleanConfiguration\x12\x16\n" +
	"\x06config\x18\x01 \x01(\bR\x06config\"*\n" +
	"\x10IntConfiguration\x12\x16\n" +
	"\x06config\x18\x01 \x01(\x05R\x06config\"-\n" +
	"\x13DoubleConfiguration\x12\x16\n" +
	"\x06config\x18\x01 \x01(\x01R\x06config\"-\n" +
	"\x13StringConfiguration\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\"\x8b\x01\n" +
	"\x14ConfigurationRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12N\n" +
	"\x0edefault_result\x18\x02 \x01(\v2\".configuration.ConfigurationResultH\x00R\rdefaultResult\x88\x01\x01B\x11\n" +
	"\x0f_default_result2\xeb\x02\n" +
	"\rConfiguration\x12X\n" +
	"\n" +
	"GetBoolean\x12#.configuration.ConfigurationRequest\x1a#.configuration.BooleanConfiguration\"\x00\x12P\n" +
	"\x06GetInt\x12#.configuration.ConfigurationRequest\x1a\x1f.configuration.IntConfiguration\"\x00\x12V\n" +
	"\tGetDouble\x12#.configuration.ConfigurationRequest\x1a\".configuration.DoubleConfiguration\"\x00\x12V\n" +
	"\tGetString\x12#.configuration.ConfigurationRequest\x1a\".configuration.StringConfiguration\"\x00B5Z3github.com/himalayo/clusterfuck/configuration/protob\x06proto3"

var (
	file_configuration_proto_rawDescOnce sync.Once
	file_configuration_proto_rawDescData []byte
)

func file_configuration_proto_rawDescGZIP() []byte {
	file_configuration_proto_rawDescOnce.Do(func() {
		file_configuration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configuration_proto_rawDesc), len(file_configuration_proto_rawDesc)))
	})
	return file_configuration_proto_rawDescData
}

var file_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_configuration_proto_goTypes = []any{
	(*ConfigurationResult)(nil),  // 0: configuration.ConfigurationResult
	(*BooleanConfiguration)(nil), // 1: configuration.BooleanConfiguration
	(*IntConfiguration)(nil),     // 2: configuration.IntConfiguration
	(*DoubleConfiguration)(nil),  // 3: configuration.DoubleConfiguration
	(*StringConfiguration)(nil),  // 4: configuration.StringConfiguration
	(*ConfigurationRequest)(nil), // 5: configuration.ConfigurationRequest
}
var file_configuration_proto_depIdxs = []int32{
	1, // 0: configuration.ConfigurationResult.boolean_config:type_name -> configuration.BooleanConfiguration
	2, // 1: configuration.ConfigurationResult.int_config:type_name -> configuration.IntConfiguration
	3, // 2: configuration.ConfigurationResult.double_config:type_name -> configuration.DoubleConfiguration
	4, // 3: configuration.ConfigurationResult.string_config:type_name -> configuration.StringConfiguration
	0, // 4: configuration.ConfigurationRequest.default_result:type_name -> configuration.ConfigurationResult
	5, // 5: configuration.Configuration.GetBoolean:input_type -> configuration.ConfigurationRequest
	5, // 6: configuration.Configuration.GetInt:input_type -> configuration.ConfigurationRequest
	5, // 7: configuration.Configuration.GetDouble:input_type -> configuration.ConfigurationRequest
	5, // 8: configuration.Configuration.GetString:input_type -> configuration.ConfigurationRequest
	1, // 9: configuration.Configuration.GetBoolean:output_type -> configuration.BooleanConfiguration
	2, // 10: configuration.Configuration.GetInt:output_type -> configuration.IntConfiguration
	3, // 11: configuration.Configuration.GetDouble:output_type -> configuration.DoubleConfiguration
	4, // 12: configuration.Configuration.GetString:output_type -> configuration.StringConfiguration
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_configuration_proto_init() }
func file_configuration_proto_init() {
	if File_configuration_proto != nil {
		return
	}
	file_configuration_proto_msgTypes[0].OneofWrappers = []any{
		(*ConfigurationResult_BooleanConfig)(nil),
		(*ConfigurationResult_IntConfig)(nil),
		(*ConfigurationResult_DoubleConfig)(nil),
		(*ConfigurationResult_StringConfig)(nil),
	}
	file_configuration_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configuration_proto_rawDesc), len(file_configuration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_configuration_proto_goTypes,
		DependencyIndexes: file_configuration_proto_depIdxs,
		MessageInfos:      file_configuration_proto_msgTypes,
	}.Build()
	File_configuration_proto = out.File
	file_configuration_proto_goTypes = nil
	file_configuration_proto_depIdxs = nil
}
