// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: permission.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Permissions_GetRank_FullMethodName         = "/permission.Permissions/GetRank"
	Permissions_GetRankByName_FullMethodName   = "/permission.Permissions/GetRankByName"
	Permissions_CheckRankExists_FullMethodName = "/permission.Permissions/CheckRankExists"
	Permissions_GetAllRanks_FullMethodName     = "/permission.Permissions/GetAllRanks"
	Permissions_GetPermission_FullMethodName   = "/permission.Permissions/GetPermission"
	Permissions_GetRankLevel_FullMethodName    = "/permission.Permissions/GetRankLevel"
)

// PermissionsClient is the client API for Permissions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PermissionsClient interface {
	GetRank(ctx context.Context, in *RankId, opts ...grpc.CallOption) (*Rank, error)
	GetRankByName(ctx context.Context, in *RankName, opts ...grpc.CallOption) (*Rank, error)
	CheckRankExists(ctx context.Context, in *RankId, opts ...grpc.CallOption) (*RankExists, error)
	GetAllRanks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RankList, error)
	GetPermission(ctx context.Context, in *RankPermission, opts ...grpc.CallOption) (*Permission, error)
	GetRankLevel(ctx context.Context, in *RankId, opts ...grpc.CallOption) (*Level, error)
}

type permissionsClient struct {
	cc grpc.ClientConnInterface
}

func NewPermissionsClient(cc grpc.ClientConnInterface) PermissionsClient {
	return &permissionsClient{cc}
}

func (c *permissionsClient) GetRank(ctx context.Context, in *RankId, opts ...grpc.CallOption) (*Rank, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Rank)
	err := c.cc.Invoke(ctx, Permissions_GetRank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionsClient) GetRankByName(ctx context.Context, in *RankName, opts ...grpc.CallOption) (*Rank, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Rank)
	err := c.cc.Invoke(ctx, Permissions_GetRankByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionsClient) CheckRankExists(ctx context.Context, in *RankId, opts ...grpc.CallOption) (*RankExists, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RankExists)
	err := c.cc.Invoke(ctx, Permissions_CheckRankExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionsClient) GetAllRanks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RankList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RankList)
	err := c.cc.Invoke(ctx, Permissions_GetAllRanks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionsClient) GetPermission(ctx context.Context, in *RankPermission, opts ...grpc.CallOption) (*Permission, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Permission)
	err := c.cc.Invoke(ctx, Permissions_GetPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionsClient) GetRankLevel(ctx context.Context, in *RankId, opts ...grpc.CallOption) (*Level, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Level)
	err := c.cc.Invoke(ctx, Permissions_GetRankLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PermissionsServer is the server API for Permissions service.
// All implementations must embed UnimplementedPermissionsServer
// for forward compatibility.
type PermissionsServer interface {
	GetRank(context.Context, *RankId) (*Rank, error)
	GetRankByName(context.Context, *RankName) (*Rank, error)
	CheckRankExists(context.Context, *RankId) (*RankExists, error)
	GetAllRanks(context.Context, *Empty) (*RankList, error)
	GetPermission(context.Context, *RankPermission) (*Permission, error)
	GetRankLevel(context.Context, *RankId) (*Level, error)
	mustEmbedUnimplementedPermissionsServer()
}

// UnimplementedPermissionsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPermissionsServer struct{}

func (UnimplementedPermissionsServer) GetRank(context.Context, *RankId) (*Rank, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRank not implemented")
}
func (UnimplementedPermissionsServer) GetRankByName(context.Context, *RankName) (*Rank, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRankByName not implemented")
}
func (UnimplementedPermissionsServer) CheckRankExists(context.Context, *RankId) (*RankExists, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckRankExists not implemented")
}
func (UnimplementedPermissionsServer) GetAllRanks(context.Context, *Empty) (*RankList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRanks not implemented")
}
func (UnimplementedPermissionsServer) GetPermission(context.Context, *RankPermission) (*Permission, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPermission not implemented")
}
func (UnimplementedPermissionsServer) GetRankLevel(context.Context, *RankId) (*Level, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRankLevel not implemented")
}
func (UnimplementedPermissionsServer) mustEmbedUnimplementedPermissionsServer() {}
func (UnimplementedPermissionsServer) testEmbeddedByValue()                     {}

// UnsafePermissionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PermissionsServer will
// result in compilation errors.
type UnsafePermissionsServer interface {
	mustEmbedUnimplementedPermissionsServer()
}

func RegisterPermissionsServer(s grpc.ServiceRegistrar, srv PermissionsServer) {
	// If the following call pancis, it indicates UnimplementedPermissionsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Permissions_ServiceDesc, srv)
}

func _Permissions_GetRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionsServer).GetRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permissions_GetRank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionsServer).GetRank(ctx, req.(*RankId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permissions_GetRankByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionsServer).GetRankByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permissions_GetRankByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionsServer).GetRankByName(ctx, req.(*RankName))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permissions_CheckRankExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionsServer).CheckRankExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permissions_CheckRankExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionsServer).CheckRankExists(ctx, req.(*RankId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permissions_GetAllRanks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionsServer).GetAllRanks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permissions_GetAllRanks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionsServer).GetAllRanks(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permissions_GetPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankPermission)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionsServer).GetPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permissions_GetPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionsServer).GetPermission(ctx, req.(*RankPermission))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permissions_GetRankLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionsServer).GetRankLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permissions_GetRankLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionsServer).GetRankLevel(ctx, req.(*RankId))
	}
	return interceptor(ctx, in, info, handler)
}

// Permissions_ServiceDesc is the grpc.ServiceDesc for Permissions service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Permissions_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "permission.Permissions",
	HandlerType: (*PermissionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRank",
			Handler:    _Permissions_GetRank_Handler,
		},
		{
			MethodName: "GetRankByName",
			Handler:    _Permissions_GetRankByName_Handler,
		},
		{
			MethodName: "CheckRankExists",
			Handler:    _Permissions_CheckRankExists_Handler,
		},
		{
			MethodName: "GetAllRanks",
			Handler:    _Permissions_GetAllRanks_Handler,
		},
		{
			MethodName: "GetPermission",
			Handler:    _Permissions_GetPermission_Handler,
		},
		{
			MethodName: "GetRankLevel",
			Handler:    _Permissions_GetRankLevel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "permission.proto",
}
