syntax = "proto3";

package permission;

option go_package = "github.com/himalayo/clusterfuck/subscription/proto";

service Permissions {
	rpc GetRank (RankId) returns (Rank) {}
	rpc GetRankByName (RankName) returns (Rank) {}
	rpc CheckRankExists (RankId) returns (RankExists) {}
	rpc GetAllRanks (Empty) returns (RankList) {}
	rpc GetPermission (RankPermission) returns (Permission) {}
	rpc GetRankLevel (RankId) returns (Level) {}
}

message Empty {}

message Level {
	int32 level = 1;
}

message RankPermission {
	int32 rank_id = 1;
	string permission_key = 2;
}

message RankExists {
	bool exists = 1;
}

message RankName {
	string name = 1;
}

message RankId {
	int32 id = 1;
}

enum PermissionSetting {
	DISALLOWED = 0;
	ALLOWED = 1;
	ROOM_OWNER = 2;
}

message Permission {
	string key = 1;
	PermissionSetting setting = 2;
}

message RankList {
	repeated Rank elements = 1;
}

message Rank {
	int32 id = 1;
	int32 level = 2;
	map<string, Permission> permissions = 3;
	map<string, string> variables = 4;
	string name = 5;
	string badge = 6;
	int32 roomEffect = 7;
	bool log_commands = 8;
	string prefix = 9;
	string prefix_color = 10;
	int32 diamonds_timer_amount = 11;
	int32 credits_timer_amount = 12;
	int32 pixels_timer_amount = 13;
	int32 gotw_timer_amount = 14;
}
