// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: permission.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PermissionSetting int32

const (
	PermissionSetting_DISALLOWED PermissionSetting = 0
	PermissionSetting_ALLOWED    PermissionSetting = 1
	PermissionSetting_ROOM_OWNER PermissionSetting = 2
)

// Enum value maps for PermissionSetting.
var (
	PermissionSetting_name = map[int32]string{
		0: "DISALLOWED",
		1: "ALLOWED",
		2: "ROOM_OWNER",
	}
	PermissionSetting_value = map[string]int32{
		"DISALLOWED": 0,
		"ALLOWED":    1,
		"ROOM_OWNER": 2,
	}
)

func (x PermissionSetting) Enum() *PermissionSetting {
	p := new(PermissionSetting)
	*p = x
	return p
}

func (x PermissionSetting) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionSetting) Descriptor() protoreflect.EnumDescriptor {
	return file_permission_proto_enumTypes[0].Descriptor()
}

func (PermissionSetting) Type() protoreflect.EnumType {
	return &file_permission_proto_enumTypes[0]
}

func (x PermissionSetting) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionSetting.Descriptor instead.
func (PermissionSetting) EnumDescriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{0}
}

type Level struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Level) Reset() {
	*x = Level{}
	mi := &file_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Level) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Level) ProtoMessage() {}

func (x *Level) ProtoReflect() protoreflect.Message {
	mi := &file_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Level.ProtoReflect.Descriptor instead.
func (*Level) Descriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{1}
}

func (x *Level) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type RankPermission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankId        int32                  `protobuf:"varint,1,opt,name=rank_id,json=rankId,proto3" json:"rank_id,omitempty"`
	PermissionKey string                 `protobuf:"bytes,2,opt,name=permission_key,json=permissionKey,proto3" json:"permission_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankPermission) Reset() {
	*x = RankPermission{}
	mi := &file_permission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankPermission) ProtoMessage() {}

func (x *RankPermission) ProtoReflect() protoreflect.Message {
	mi := &file_permission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankPermission.ProtoReflect.Descriptor instead.
func (*RankPermission) Descriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{2}
}

func (x *RankPermission) GetRankId() int32 {
	if x != nil {
		return x.RankId
	}
	return 0
}

func (x *RankPermission) GetPermissionKey() string {
	if x != nil {
		return x.PermissionKey
	}
	return ""
}

type RankExists struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankExists) Reset() {
	*x = RankExists{}
	mi := &file_permission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankExists) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankExists) ProtoMessage() {}

func (x *RankExists) ProtoReflect() protoreflect.Message {
	mi := &file_permission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankExists.ProtoReflect.Descriptor instead.
func (*RankExists) Descriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{3}
}

func (x *RankExists) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type RankName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankName) Reset() {
	*x = RankName{}
	mi := &file_permission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankName) ProtoMessage() {}

func (x *RankName) ProtoReflect() protoreflect.Message {
	mi := &file_permission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankName.ProtoReflect.Descriptor instead.
func (*RankName) Descriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{4}
}

func (x *RankName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RankId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankId) Reset() {
	*x = RankId{}
	mi := &file_permission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankId) ProtoMessage() {}

func (x *RankId) ProtoReflect() protoreflect.Message {
	mi := &file_permission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankId.ProtoReflect.Descriptor instead.
func (*RankId) Descriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{5}
}

func (x *RankId) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Setting       PermissionSetting      `protobuf:"varint,2,opt,name=setting,proto3,enum=permission.PermissionSetting" json:"setting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_permission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_permission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{6}
}

func (x *Permission) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Permission) GetSetting() PermissionSetting {
	if x != nil {
		return x.Setting
	}
	return PermissionSetting_DISALLOWED
}

type RankList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []*Rank                `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankList) Reset() {
	*x = RankList{}
	mi := &file_permission_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankList) ProtoMessage() {}

func (x *RankList) ProtoReflect() protoreflect.Message {
	mi := &file_permission_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankList.ProtoReflect.Descriptor instead.
func (*RankList) Descriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{7}
}

func (x *RankList) GetElements() []*Rank {
	if x != nil {
		return x.Elements
	}
	return nil
}

type Rank struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Level               int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Permissions         map[string]*Permission `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Variables           map[string]string      `protobuf:"bytes,4,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Name                string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Badge               string                 `protobuf:"bytes,6,opt,name=badge,proto3" json:"badge,omitempty"`
	RoomEffect          int32                  `protobuf:"varint,7,opt,name=roomEffect,proto3" json:"roomEffect,omitempty"`
	LogCommands         bool                   `protobuf:"varint,8,opt,name=log_commands,json=logCommands,proto3" json:"log_commands,omitempty"`
	Prefix              string                 `protobuf:"bytes,9,opt,name=prefix,proto3" json:"prefix,omitempty"`
	PrefixColor         string                 `protobuf:"bytes,10,opt,name=prefix_color,json=prefixColor,proto3" json:"prefix_color,omitempty"`
	DiamondsTimerAmount int32                  `protobuf:"varint,11,opt,name=diamonds_timer_amount,json=diamondsTimerAmount,proto3" json:"diamonds_timer_amount,omitempty"`
	CreditsTimerAmount  int32                  `protobuf:"varint,12,opt,name=credits_timer_amount,json=creditsTimerAmount,proto3" json:"credits_timer_amount,omitempty"`
	PixelsTimerAmount   int32                  `protobuf:"varint,13,opt,name=pixels_timer_amount,json=pixelsTimerAmount,proto3" json:"pixels_timer_amount,omitempty"`
	GotwTimerAmount     int32                  `protobuf:"varint,14,opt,name=gotw_timer_amount,json=gotwTimerAmount,proto3" json:"gotw_timer_amount,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Rank) Reset() {
	*x = Rank{}
	mi := &file_permission_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rank) ProtoMessage() {}

func (x *Rank) ProtoReflect() protoreflect.Message {
	mi := &file_permission_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rank.ProtoReflect.Descriptor instead.
func (*Rank) Descriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{8}
}

func (x *Rank) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Rank) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Rank) GetPermissions() map[string]*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Rank) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *Rank) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rank) GetBadge() string {
	if x != nil {
		return x.Badge
	}
	return ""
}

func (x *Rank) GetRoomEffect() int32 {
	if x != nil {
		return x.RoomEffect
	}
	return 0
}

func (x *Rank) GetLogCommands() bool {
	if x != nil {
		return x.LogCommands
	}
	return false
}

func (x *Rank) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Rank) GetPrefixColor() string {
	if x != nil {
		return x.PrefixColor
	}
	return ""
}

func (x *Rank) GetDiamondsTimerAmount() int32 {
	if x != nil {
		return x.DiamondsTimerAmount
	}
	return 0
}

func (x *Rank) GetCreditsTimerAmount() int32 {
	if x != nil {
		return x.CreditsTimerAmount
	}
	return 0
}

func (x *Rank) GetPixelsTimerAmount() int32 {
	if x != nil {
		return x.PixelsTimerAmount
	}
	return 0
}

func (x *Rank) GetGotwTimerAmount() int32 {
	if x != nil {
		return x.GotwTimerAmount
	}
	return 0
}

type Perk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Requirement   string                 `protobuf:"bytes,2,opt,name=requirement,proto3" json:"requirement,omitempty"`
	Value         bool                   `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Perk) Reset() {
	*x = Perk{}
	mi := &file_permission_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Perk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Perk) ProtoMessage() {}

func (x *Perk) ProtoReflect() protoreflect.Message {
	mi := &file_permission_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Perk.ProtoReflect.Descriptor instead.
func (*Perk) Descriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{9}
}

func (x *Perk) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Perk) GetRequirement() string {
	if x != nil {
		return x.Requirement
	}
	return ""
}

func (x *Perk) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type RankPerks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []*Perk                `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankPerks) Reset() {
	*x = RankPerks{}
	mi := &file_permission_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankPerks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankPerks) ProtoMessage() {}

func (x *RankPerks) ProtoReflect() protoreflect.Message {
	mi := &file_permission_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankPerks.ProtoReflect.Descriptor instead.
func (*RankPerks) Descriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{10}
}

func (x *RankPerks) GetElements() []*Perk {
	if x != nil {
		return x.Elements
	}
	return nil
}

var File_permission_proto protoreflect.FileDescriptor

const file_permission_proto_rawDesc = "" +
	"\n" +
	"\x10permission.proto\x12\n" +
	"permission\"\a\n" +
	"\x05Empty\"\x1d\n" +
	"\x05Level\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\"P\n" +
	"\x0eRankPermission\x12\x17\n" +
	"\arank_id\x18\x01 \x01(\x05R\x06rankId\x12%\n" +
	"\x0epermission_key\x18\x02 \x01(\tR\rpermissionKey\"$\n" +
	"\n" +
	"RankExists\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"\x1e\n" +
	"\bRankName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x18\n" +
	"\x06RankId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"W\n" +
	"\n" +
	"Permission\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\asetting\x18\x02 \x01(\x0e2\x1d.permission.PermissionSettingR\asetting\"8\n" +
	"\bRankList\x12,\n" +
	"\belements\x18\x01 \x03(\v2\x10.permission.RankR\belements\"\xb0\x05\n" +
	"\x04Rank\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12C\n" +
	"\vpermissions\x18\x03 \x03(\v2!.permission.Rank.PermissionsEntryR\vpermissions\x12=\n" +
	"\tvariables\x18\x04 \x03(\v2\x1f.permission.Rank.VariablesEntryR\tvariables\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x14\n" +
	"\x05badge\x18\x06 \x01(\tR\x05badge\x12\x1e\n" +
	"\n" +
	"roomEffect\x18\a \x01(\x05R\n" +
	"roomEffect\x12!\n" +
	"\flog_commands\x18\b \x01(\bR\vlogCommands\x12\x16\n" +
	"\x06prefix\x18\t \x01(\tR\x06prefix\x12!\n" +
	"\fprefix_color\x18\n" +
	" \x01(\tR\vprefixColor\x122\n" +
	"\x15diamonds_timer_amount\x18\v \x01(\x05R\x13diamondsTimerAmount\x120\n" +
	"\x14credits_timer_amount\x18\f \x01(\x05R\x12creditsTimerAmount\x12.\n" +
	"\x13pixels_timer_amount\x18\r \x01(\x05R\x11pixelsTimerAmount\x12*\n" +
	"\x11gotw_timer_amount\x18\x0e \x01(\x05R\x0fgotwTimerAmount\x1aV\n" +
	"\x10PermissionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.permission.PermissionR\x05value:\x028\x01\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\x04Perk\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12 \n" +
	"\vrequirement\x18\x02 \x01(\tR\vrequirement\x12\x14\n" +
	"\x05value\x18\x03 \x01(\bR\x05value\"9\n" +
	"\tRankPerks\x12,\n" +
	"\belements\x18\x01 \x03(\v2\x10.permission.PerkR\belements*@\n" +
	"\x11PermissionSetting\x12\x0e\n" +
	"\n" +
	"DISALLOWED\x10\x00\x12\v\n" +
	"\aALLOWED\x10\x01\x12\x0e\n" +
	"\n" +
	"ROOM_OWNER\x10\x022\xb3\x03\n" +
	"\vPermissions\x121\n" +
	"\aGetRank\x12\x12.permission.RankId\x1a\x10.permission.Rank\"\x00\x129\n" +
	"\rGetRankByName\x12\x14.permission.RankName\x1a\x10.permission.Rank\"\x00\x12?\n" +
	"\x0fCheckRankExists\x12\x12.permission.RankId\x1a\x16.permission.RankExists\"\x00\x128\n" +
	"\vGetAllRanks\x12\x11.permission.Empty\x1a\x14.permission.RankList\"\x00\x12E\n" +
	"\rGetPermission\x12\x1a.permission.RankPermission\x1a\x16.permission.Permission\"\x00\x127\n" +
	"\fGetRankLevel\x12\x12.permission.RankId\x1a\x11.permission.Level\"\x00\x12;\n" +
	"\fGetRankPerks\x12\x12.permission.RankId\x1a\x15.permission.RankPerks\"\x00B4Z2github.com/himalayo/clusterfuck/subscription/protob\x06proto3"

var (
	file_permission_proto_rawDescOnce sync.Once
	file_permission_proto_rawDescData []byte
)

func file_permission_proto_rawDescGZIP() []byte {
	file_permission_proto_rawDescOnce.Do(func() {
		file_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_permission_proto_rawDesc), len(file_permission_proto_rawDesc)))
	})
	return file_permission_proto_rawDescData
}

var file_permission_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_permission_proto_goTypes = []any{
	(PermissionSetting)(0), // 0: permission.PermissionSetting
	(*Empty)(nil),          // 1: permission.Empty
	(*Level)(nil),          // 2: permission.Level
	(*RankPermission)(nil), // 3: permission.RankPermission
	(*RankExists)(nil),     // 4: permission.RankExists
	(*RankName)(nil),       // 5: permission.RankName
	(*RankId)(nil),         // 6: permission.RankId
	(*Permission)(nil),     // 7: permission.Permission
	(*RankList)(nil),       // 8: permission.RankList
	(*Rank)(nil),           // 9: permission.Rank
	(*Perk)(nil),           // 10: permission.Perk
	(*RankPerks)(nil),      // 11: permission.RankPerks
	nil,                    // 12: permission.Rank.PermissionsEntry
	nil,                    // 13: permission.Rank.VariablesEntry
}
var file_permission_proto_depIdxs = []int32{
	0,  // 0: permission.Permission.setting:type_name -> permission.PermissionSetting
	9,  // 1: permission.RankList.elements:type_name -> permission.Rank
	12, // 2: permission.Rank.permissions:type_name -> permission.Rank.PermissionsEntry
	13, // 3: permission.Rank.variables:type_name -> permission.Rank.VariablesEntry
	10, // 4: permission.RankPerks.elements:type_name -> permission.Perk
	7,  // 5: permission.Rank.PermissionsEntry.value:type_name -> permission.Permission
	6,  // 6: permission.Permissions.GetRank:input_type -> permission.RankId
	5,  // 7: permission.Permissions.GetRankByName:input_type -> permission.RankName
	6,  // 8: permission.Permissions.CheckRankExists:input_type -> permission.RankId
	1,  // 9: permission.Permissions.GetAllRanks:input_type -> permission.Empty
	3,  // 10: permission.Permissions.GetPermission:input_type -> permission.RankPermission
	6,  // 11: permission.Permissions.GetRankLevel:input_type -> permission.RankId
	6,  // 12: permission.Permissions.GetRankPerks:input_type -> permission.RankId
	9,  // 13: permission.Permissions.GetRank:output_type -> permission.Rank
	9,  // 14: permission.Permissions.GetRankByName:output_type -> permission.Rank
	4,  // 15: permission.Permissions.CheckRankExists:output_type -> permission.RankExists
	8,  // 16: permission.Permissions.GetAllRanks:output_type -> permission.RankList
	7,  // 17: permission.Permissions.GetPermission:output_type -> permission.Permission
	2,  // 18: permission.Permissions.GetRankLevel:output_type -> permission.Level
	11, // 19: permission.Permissions.GetRankPerks:output_type -> permission.RankPerks
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_permission_proto_init() }
func file_permission_proto_init() {
	if File_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_permission_proto_rawDesc), len(file_permission_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_permission_proto_goTypes,
		DependencyIndexes: file_permission_proto_depIdxs,
		EnumInfos:         file_permission_proto_enumTypes,
		MessageInfos:      file_permission_proto_msgTypes,
	}.Build()
	File_permission_proto = out.File
	file_permission_proto_goTypes = nil
	file_permission_proto_depIdxs = nil
}
