syntax = "proto3";

package player;

option go_package = "github.com/himalayo/clusterfuck/player/proto";

service Player {
	rpc LoginPlayer (Ticket) returns (LoginStatus) {}
	rpc GetUserData (Ticket) returns (UserData) {}
	rpc GetUserHCData (Ticket) returns (UserHCData) {}
	rpc GetUserDataById (UserId) returns (UserData) {}
}

message UserId {
	int32 id = 1;
}

message Ticket {
	string sso = 1;
}

message LoginStatus {
	bool success = 1;
}

message UserData {
	int32 id = 1;
	string username = 2;
	string look = 3;
	string auth_ticket = 4;
	string motto = 5;
	int32 home_room = 6;
	int32 rank = 7;
	string gender = 8;
}

message UserHCData {
	int32 last_hc_payday = 1;
	int32 hc_gifts_claimed = 2;
}

message LoginEvent {
	string id = 1;
	string type = 2;
	UserData user_data = 3;
}