// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: player.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ticket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sso           string                 `protobuf:"bytes,1,opt,name=sso,proto3" json:"sso,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	mi := &file_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{0}
}

func (x *Ticket) GetSso() string {
	if x != nil {
		return x.Sso
	}
	return ""
}

type LoginStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginStatus) Reset() {
	*x = LoginStatus{}
	mi := &file_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginStatus) ProtoMessage() {}

func (x *LoginStatus) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginStatus.ProtoReflect.Descriptor instead.
func (*LoginStatus) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{1}
}

func (x *LoginStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Look          string                 `protobuf:"bytes,3,opt,name=look,proto3" json:"look,omitempty"`
	AuthTicket    string                 `protobuf:"bytes,4,opt,name=auth_ticket,json=authTicket,proto3" json:"auth_ticket,omitempty"`
	Motto         string                 `protobuf:"bytes,5,opt,name=motto,proto3" json:"motto,omitempty"`
	HomeRoom      int32                  `protobuf:"varint,6,opt,name=home_room,json=homeRoom,proto3" json:"home_room,omitempty"`
	Rank          int32                  `protobuf:"varint,7,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserData) Reset() {
	*x = UserData{}
	mi := &file_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{2}
}

func (x *UserData) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserData) GetLook() string {
	if x != nil {
		return x.Look
	}
	return ""
}

func (x *UserData) GetAuthTicket() string {
	if x != nil {
		return x.AuthTicket
	}
	return ""
}

func (x *UserData) GetMotto() string {
	if x != nil {
		return x.Motto
	}
	return ""
}

func (x *UserData) GetHomeRoom() int32 {
	if x != nil {
		return x.HomeRoom
	}
	return 0
}

func (x *UserData) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type LoginEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	UserData      *UserData              `protobuf:"bytes,3,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginEvent) Reset() {
	*x = LoginEvent{}
	mi := &file_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginEvent) ProtoMessage() {}

func (x *LoginEvent) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginEvent.ProtoReflect.Descriptor instead.
func (*LoginEvent) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{3}
}

func (x *LoginEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoginEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LoginEvent) GetUserData() *UserData {
	if x != nil {
		return x.UserData
	}
	return nil
}

var File_player_proto protoreflect.FileDescriptor

const file_player_proto_rawDesc = "" +
	"\n" +
	"\fplayer.proto\x12\x06player\"\x1a\n" +
	"\x06Ticket\x12\x10\n" +
	"\x03sso\x18\x01 \x01(\tR\x03sso\"'\n" +
	"\vLoginStatus\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb2\x01\n" +
	"\bUserData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04look\x18\x03 \x01(\tR\x04look\x12\x1f\n" +
	"\vauth_ticket\x18\x04 \x01(\tR\n" +
	"authTicket\x12\x14\n" +
	"\x05motto\x18\x05 \x01(\tR\x05motto\x12\x1b\n" +
	"\thome_room\x18\x06 \x01(\x05R\bhomeRoom\x12\x12\n" +
	"\x04rank\x18\a \x01(\x05R\x04rank\"_\n" +
	"\n" +
	"LoginEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12-\n" +
	"\tuser_data\x18\x03 \x01(\v2\x10.player.UserDataR\buserData2q\n" +
	"\x06Player\x124\n" +
	"\vLoginPlayer\x12\x0e.player.Ticket\x1a\x13.player.LoginStatus\"\x00\x121\n" +
	"\vGetUserData\x12\x0e.player.Ticket\x1a\x10.player.UserData\"\x00B.Z,github.com/himalayo/clusterfuck/player/protob\x06proto3"

var (
	file_player_proto_rawDescOnce sync.Once
	file_player_proto_rawDescData []byte
)

func file_player_proto_rawDescGZIP() []byte {
	file_player_proto_rawDescOnce.Do(func() {
		file_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)))
	})
	return file_player_proto_rawDescData
}

var file_player_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_player_proto_goTypes = []any{
	(*Ticket)(nil),      // 0: player.Ticket
	(*LoginStatus)(nil), // 1: player.LoginStatus
	(*UserData)(nil),    // 2: player.UserData
	(*LoginEvent)(nil),  // 3: player.LoginEvent
}
var file_player_proto_depIdxs = []int32{
	2, // 0: player.LoginEvent.user_data:type_name -> player.UserData
	0, // 1: player.Player.LoginPlayer:input_type -> player.Ticket
	0, // 2: player.Player.GetUserData:input_type -> player.Ticket
	1, // 3: player.Player.LoginPlayer:output_type -> player.LoginStatus
	2, // 4: player.Player.GetUserData:output_type -> player.UserData
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_player_proto_init() }
func file_player_proto_init() {
	if File_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_player_proto_goTypes,
		DependencyIndexes: file_player_proto_depIdxs,
		MessageInfos:      file_player_proto_msgTypes,
	}.Build()
	File_player_proto = out.File
	file_player_proto_goTypes = nil
	file_player_proto_depIdxs = nil
}
