// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: items.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_items_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_items_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_items_proto_rawDescGZIP(), []int{0}
}

type ItemList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemList) Reset() {
	*x = ItemList{}
	mi := &file_items_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemList) ProtoMessage() {}

func (x *ItemList) ProtoReflect() protoreflect.Message {
	mi := &file_items_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemList.ProtoReflect.Descriptor instead.
func (*ItemList) Descriptor() ([]byte, []int) {
	return file_items_proto_rawDescGZIP(), []int{1}
}

func (x *ItemList) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ItemRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*ItemRequest_ItemId
	//	*ItemRequest_ItemName
	Request       isItemRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRequest) Reset() {
	*x = ItemRequest{}
	mi := &file_items_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRequest) ProtoMessage() {}

func (x *ItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_items_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRequest.ProtoReflect.Descriptor instead.
func (*ItemRequest) Descriptor() ([]byte, []int) {
	return file_items_proto_rawDescGZIP(), []int{2}
}

func (x *ItemRequest) GetRequest() isItemRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ItemRequest) GetItemId() int32 {
	if x != nil {
		if x, ok := x.Request.(*ItemRequest_ItemId); ok {
			return x.ItemId
		}
	}
	return 0
}

func (x *ItemRequest) GetItemName() string {
	if x != nil {
		if x, ok := x.Request.(*ItemRequest_ItemName); ok {
			return x.ItemName
		}
	}
	return ""
}

type isItemRequest_Request interface {
	isItemRequest_Request()
}

type ItemRequest_ItemId struct {
	ItemId int32 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3,oneof"`
}

type ItemRequest_ItemName struct {
	ItemName string `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3,oneof"`
}

func (*ItemRequest_ItemId) isItemRequest_Request() {}

func (*ItemRequest_ItemName) isItemRequest_Request() {}

type Item struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SpriteId            int32                  `protobuf:"varint,2,opt,name=sprite_id,json=spriteId,proto3" json:"sprite_id,omitempty"`
	Name                string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	FullName            string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	FurnitureType       string                 `protobuf:"bytes,5,opt,name=furniture_type,json=furnitureType,proto3" json:"furniture_type,omitempty"`
	Width               int32                  `protobuf:"varint,6,opt,name=width,proto3" json:"width,omitempty"`
	Length              int32                  `protobuf:"varint,7,opt,name=length,proto3" json:"length,omitempty"`
	Height              float64                `protobuf:"fixed64,8,opt,name=height,proto3" json:"height,omitempty"`
	AllowStack          bool                   `protobuf:"varint,9,opt,name=allow_stack,json=allowStack,proto3" json:"allow_stack,omitempty"`
	AllowWalk           int32                  `protobuf:"varint,10,opt,name=allow_walk,json=allowWalk,proto3" json:"allow_walk,omitempty"`
	AllowSit            int32                  `protobuf:"varint,11,opt,name=allow_sit,json=allowSit,proto3" json:"allow_sit,omitempty"`
	AllowLay            int32                  `protobuf:"varint,12,opt,name=allow_lay,json=allowLay,proto3" json:"allow_lay,omitempty"`
	AllowRecycle        bool                   `protobuf:"varint,13,opt,name=allow_recycle,json=allowRecycle,proto3" json:"allow_recycle,omitempty"`
	AllowTrade          bool                   `protobuf:"varint,14,opt,name=allow_trade,json=allowTrade,proto3" json:"allow_trade,omitempty"`
	AllowMarketplace    bool                   `protobuf:"varint,15,opt,name=allow_marketplace,json=allowMarketplace,proto3" json:"allow_marketplace,omitempty"`
	AllowGift           bool                   `protobuf:"varint,16,opt,name=allow_gift,json=allowGift,proto3" json:"allow_gift,omitempty"`
	AllowInventoryStack bool                   `protobuf:"varint,17,opt,name=allow_inventory_stack,json=allowInventoryStack,proto3" json:"allow_inventory_stack,omitempty"`
	StateCount          int32                  `protobuf:"varint,18,opt,name=state_count,json=stateCount,proto3" json:"state_count,omitempty"`
	EffectM             int32                  `protobuf:"varint,19,opt,name=effect_m,json=effectM,proto3" json:"effect_m,omitempty"`
	EffectF             int32                  `protobuf:"varint,20,opt,name=effect_f,json=effectF,proto3" json:"effect_f,omitempty"`
	VendingItems        []int32                `protobuf:"varint,21,rep,packed,name=vending_items,json=vendingItems,proto3" json:"vending_items,omitempty"`
	MultiHeights        []float64              `protobuf:"fixed64,22,rep,packed,name=multi_heights,json=multiHeights,proto3" json:"multi_heights,omitempty"`
	CustomParams        string                 `protobuf:"bytes,23,opt,name=custom_params,json=customParams,proto3" json:"custom_params,omitempty"`
	ClothingOnWalk      string                 `protobuf:"bytes,24,opt,name=clothing_on_walk,json=clothingOnWalk,proto3" json:"clothing_on_walk,omitempty"`
	InteractionType     string                 `protobuf:"bytes,25,opt,name=interaction_type,json=interactionType,proto3" json:"interaction_type,omitempty"`
	Rotations           int32                  `protobuf:"varint,26,opt,name=rotations,proto3" json:"rotations,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_items_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_items_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_items_proto_rawDescGZIP(), []int{3}
}

func (x *Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetSpriteId() int32 {
	if x != nil {
		return x.SpriteId
	}
	return 0
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Item) GetFurnitureType() string {
	if x != nil {
		return x.FurnitureType
	}
	return ""
}

func (x *Item) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Item) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Item) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Item) GetAllowStack() bool {
	if x != nil {
		return x.AllowStack
	}
	return false
}

func (x *Item) GetAllowWalk() int32 {
	if x != nil {
		return x.AllowWalk
	}
	return 0
}

func (x *Item) GetAllowSit() int32 {
	if x != nil {
		return x.AllowSit
	}
	return 0
}

func (x *Item) GetAllowLay() int32 {
	if x != nil {
		return x.AllowLay
	}
	return 0
}

func (x *Item) GetAllowRecycle() bool {
	if x != nil {
		return x.AllowRecycle
	}
	return false
}

func (x *Item) GetAllowTrade() bool {
	if x != nil {
		return x.AllowTrade
	}
	return false
}

func (x *Item) GetAllowMarketplace() bool {
	if x != nil {
		return x.AllowMarketplace
	}
	return false
}

func (x *Item) GetAllowGift() bool {
	if x != nil {
		return x.AllowGift
	}
	return false
}

func (x *Item) GetAllowInventoryStack() bool {
	if x != nil {
		return x.AllowInventoryStack
	}
	return false
}

func (x *Item) GetStateCount() int32 {
	if x != nil {
		return x.StateCount
	}
	return 0
}

func (x *Item) GetEffectM() int32 {
	if x != nil {
		return x.EffectM
	}
	return 0
}

func (x *Item) GetEffectF() int32 {
	if x != nil {
		return x.EffectF
	}
	return 0
}

func (x *Item) GetVendingItems() []int32 {
	if x != nil {
		return x.VendingItems
	}
	return nil
}

func (x *Item) GetMultiHeights() []float64 {
	if x != nil {
		return x.MultiHeights
	}
	return nil
}

func (x *Item) GetCustomParams() string {
	if x != nil {
		return x.CustomParams
	}
	return ""
}

func (x *Item) GetClothingOnWalk() string {
	if x != nil {
		return x.ClothingOnWalk
	}
	return ""
}

func (x *Item) GetInteractionType() string {
	if x != nil {
		return x.InteractionType
	}
	return ""
}

func (x *Item) GetRotations() int32 {
	if x != nil {
		return x.Rotations
	}
	return 0
}

var File_items_proto protoreflect.FileDescriptor

const file_items_proto_rawDesc = "" +
	"\n" +
	"\vitems.proto\x12\x05items\"\a\n" +
	"\x05Empty\"-\n" +
	"\bItemList\x12!\n" +
	"\x05items\x18\x01 \x03(\v2\v.items.ItemR\x05items\"R\n" +
	"\vItemRequest\x12\x19\n" +
	"\aitem_id\x18\x01 \x01(\x05H\x00R\x06itemId\x12\x1d\n" +
	"\titem_name\x18\x02 \x01(\tH\x00R\bitemNameB\t\n" +
	"\arequest\"\xca\x06\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tsprite_id\x18\x02 \x01(\x05R\bspriteId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\x12%\n" +
	"\x0efurniture_type\x18\x05 \x01(\tR\rfurnitureType\x12\x14\n" +
	"\x05width\x18\x06 \x01(\x05R\x05width\x12\x16\n" +
	"\x06length\x18\a \x01(\x05R\x06length\x12\x16\n" +
	"\x06height\x18\b \x01(\x01R\x06height\x12\x1f\n" +
	"\vallow_stack\x18\t \x01(\bR\n" +
	"allowStack\x12\x1d\n" +
	"\n" +
	"allow_walk\x18\n" +
	" \x01(\x05R\tallowWalk\x12\x1b\n" +
	"\tallow_sit\x18\v \x01(\x05R\ballowSit\x12\x1b\n" +
	"\tallow_lay\x18\f \x01(\x05R\ballowLay\x12#\n" +
	"\rallow_recycle\x18\r \x01(\bR\fallowRecycle\x12\x1f\n" +
	"\vallow_trade\x18\x0e \x01(\bR\n" +
	"allowTrade\x12+\n" +
	"\x11allow_marketplace\x18\x0f \x01(\bR\x10allowMarketplace\x12\x1d\n" +
	"\n" +
	"allow_gift\x18\x10 \x01(\bR\tallowGift\x122\n" +
	"\x15allow_inventory_stack\x18\x11 \x01(\bR\x13allowInventoryStack\x12\x1f\n" +
	"\vstate_count\x18\x12 \x01(\x05R\n" +
	"stateCount\x12\x19\n" +
	"\beffect_m\x18\x13 \x01(\x05R\aeffectM\x12\x19\n" +
	"\beffect_f\x18\x14 \x01(\x05R\aeffectF\x12#\n" +
	"\rvending_items\x18\x15 \x03(\x05R\fvendingItems\x12#\n" +
	"\rmulti_heights\x18\x16 \x03(\x01R\fmultiHeights\x12#\n" +
	"\rcustom_params\x18\x17 \x01(\tR\fcustomParams\x12(\n" +
	"\x10clothing_on_walk\x18\x18 \x01(\tR\x0eclothingOnWalk\x12)\n" +
	"\x10interaction_type\x18\x19 \x01(\tR\x0finteractionType\x12\x1c\n" +
	"\trotations\x18\x1a \x01(\x05R\trotations2b\n" +
	"\x05Items\x12,\n" +
	"\aGetItem\x12\x12.items.ItemRequest\x1a\v.items.Item\"\x00\x12+\n" +
	"\bGetItems\x12\f.items.Empty\x1a\x0f.items.ItemList\"\x00B1Z/github.com/himalayo/clusterfuck/api/items/protob\x06proto3"

var (
	file_items_proto_rawDescOnce sync.Once
	file_items_proto_rawDescData []byte
)

func file_items_proto_rawDescGZIP() []byte {
	file_items_proto_rawDescOnce.Do(func() {
		file_items_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_items_proto_rawDesc), len(file_items_proto_rawDesc)))
	})
	return file_items_proto_rawDescData
}

var file_items_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_items_proto_goTypes = []any{
	(*Empty)(nil),       // 0: items.Empty
	(*ItemList)(nil),    // 1: items.ItemList
	(*ItemRequest)(nil), // 2: items.ItemRequest
	(*Item)(nil),        // 3: items.Item
}
var file_items_proto_depIdxs = []int32{
	3, // 0: items.ItemList.items:type_name -> items.Item
	2, // 1: items.Items.GetItem:input_type -> items.ItemRequest
	0, // 2: items.Items.GetItems:input_type -> items.Empty
	3, // 3: items.Items.GetItem:output_type -> items.Item
	1, // 4: items.Items.GetItems:output_type -> items.ItemList
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_items_proto_init() }
func file_items_proto_init() {
	if File_items_proto != nil {
		return
	}
	file_items_proto_msgTypes[2].OneofWrappers = []any{
		(*ItemRequest_ItemId)(nil),
		(*ItemRequest_ItemName)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_items_proto_rawDesc), len(file_items_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_items_proto_goTypes,
		DependencyIndexes: file_items_proto_depIdxs,
		MessageInfos:      file_items_proto_msgTypes,
	}.Build()
	File_items_proto = out.File
	file_items_proto_goTypes = nil
	file_items_proto_depIdxs = nil
}
