// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: achievements.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Achievements_GetAchievementByName_FullMethodName          = "/achievements.Achievements/GetAchievementByName"
	Achievements_GetAchievement_FullMethodName                = "/achievements.Achievements/GetAchievement"
	Achievements_InventoryAchievementsComposer_FullMethodName = "/achievements.Achievements/InventoryAchievementsComposer"
)

// AchievementsClient is the client API for Achievements service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AchievementsClient interface {
	GetAchievementByName(ctx context.Context, in *AchievementName, opts ...grpc.CallOption) (*Achievement, error)
	GetAchievement(ctx context.Context, in *AchievementId, opts ...grpc.CallOption) (*Achievement, error)
	InventoryAchievementsComposer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Packet, error)
}

type achievementsClient struct {
	cc grpc.ClientConnInterface
}

func NewAchievementsClient(cc grpc.ClientConnInterface) AchievementsClient {
	return &achievementsClient{cc}
}

func (c *achievementsClient) GetAchievementByName(ctx context.Context, in *AchievementName, opts ...grpc.CallOption) (*Achievement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Achievement)
	err := c.cc.Invoke(ctx, Achievements_GetAchievementByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *achievementsClient) GetAchievement(ctx context.Context, in *AchievementId, opts ...grpc.CallOption) (*Achievement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Achievement)
	err := c.cc.Invoke(ctx, Achievements_GetAchievement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *achievementsClient) InventoryAchievementsComposer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Packet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Packet)
	err := c.cc.Invoke(ctx, Achievements_InventoryAchievementsComposer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AchievementsServer is the server API for Achievements service.
// All implementations must embed UnimplementedAchievementsServer
// for forward compatibility.
type AchievementsServer interface {
	GetAchievementByName(context.Context, *AchievementName) (*Achievement, error)
	GetAchievement(context.Context, *AchievementId) (*Achievement, error)
	InventoryAchievementsComposer(context.Context, *Empty) (*Packet, error)
	mustEmbedUnimplementedAchievementsServer()
}

// UnimplementedAchievementsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAchievementsServer struct{}

func (UnimplementedAchievementsServer) GetAchievementByName(context.Context, *AchievementName) (*Achievement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAchievementByName not implemented")
}
func (UnimplementedAchievementsServer) GetAchievement(context.Context, *AchievementId) (*Achievement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAchievement not implemented")
}
func (UnimplementedAchievementsServer) InventoryAchievementsComposer(context.Context, *Empty) (*Packet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InventoryAchievementsComposer not implemented")
}
func (UnimplementedAchievementsServer) mustEmbedUnimplementedAchievementsServer() {}
func (UnimplementedAchievementsServer) testEmbeddedByValue()                      {}

// UnsafeAchievementsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AchievementsServer will
// result in compilation errors.
type UnsafeAchievementsServer interface {
	mustEmbedUnimplementedAchievementsServer()
}

func RegisterAchievementsServer(s grpc.ServiceRegistrar, srv AchievementsServer) {
	// If the following call pancis, it indicates UnimplementedAchievementsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Achievements_ServiceDesc, srv)
}

func _Achievements_GetAchievementByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AchievementName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AchievementsServer).GetAchievementByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Achievements_GetAchievementByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AchievementsServer).GetAchievementByName(ctx, req.(*AchievementName))
	}
	return interceptor(ctx, in, info, handler)
}

func _Achievements_GetAchievement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AchievementId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AchievementsServer).GetAchievement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Achievements_GetAchievement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AchievementsServer).GetAchievement(ctx, req.(*AchievementId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Achievements_InventoryAchievementsComposer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AchievementsServer).InventoryAchievementsComposer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Achievements_InventoryAchievementsComposer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AchievementsServer).InventoryAchievementsComposer(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Achievements_ServiceDesc is the grpc.ServiceDesc for Achievements service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Achievements_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "achievements.Achievements",
	HandlerType: (*AchievementsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAchievementByName",
			Handler:    _Achievements_GetAchievementByName_Handler,
		},
		{
			MethodName: "GetAchievement",
			Handler:    _Achievements_GetAchievement_Handler,
		},
		{
			MethodName: "InventoryAchievementsComposer",
			Handler:    _Achievements_InventoryAchievementsComposer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "achievements.proto",
}
