// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: guilds.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Guilds_GetBases_FullMethodName            = "/configuration.Guilds/GetBases"
	Guilds_GetSymbols_FullMethodName          = "/configuration.Guilds/GetSymbols"
	Guilds_GetBaseColors_FullMethodName       = "/configuration.Guilds/GetBaseColors"
	Guilds_GetSymbolColors_FullMethodName     = "/configuration.Guilds/GetSymbolColors"
	Guilds_GetBackgroundColors_FullMethodName = "/configuration.Guilds/GetBackgroundColors"
)

// GuildsClient is the client API for Guilds service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GuildsClient interface {
	GetBases(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GuildParts, error)
	GetSymbols(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GuildParts, error)
	GetBaseColors(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GuildParts, error)
	GetSymbolColors(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GuildParts, error)
	GetBackgroundColors(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GuildParts, error)
}

type guildsClient struct {
	cc grpc.ClientConnInterface
}

func NewGuildsClient(cc grpc.ClientConnInterface) GuildsClient {
	return &guildsClient{cc}
}

func (c *guildsClient) GetBases(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GuildParts, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuildParts)
	err := c.cc.Invoke(ctx, Guilds_GetBases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildsClient) GetSymbols(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GuildParts, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuildParts)
	err := c.cc.Invoke(ctx, Guilds_GetSymbols_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildsClient) GetBaseColors(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GuildParts, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuildParts)
	err := c.cc.Invoke(ctx, Guilds_GetBaseColors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildsClient) GetSymbolColors(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GuildParts, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuildParts)
	err := c.cc.Invoke(ctx, Guilds_GetSymbolColors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guildsClient) GetBackgroundColors(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GuildParts, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuildParts)
	err := c.cc.Invoke(ctx, Guilds_GetBackgroundColors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuildsServer is the server API for Guilds service.
// All implementations must embed UnimplementedGuildsServer
// for forward compatibility.
type GuildsServer interface {
	GetBases(context.Context, *Empty) (*GuildParts, error)
	GetSymbols(context.Context, *Empty) (*GuildParts, error)
	GetBaseColors(context.Context, *Empty) (*GuildParts, error)
	GetSymbolColors(context.Context, *Empty) (*GuildParts, error)
	GetBackgroundColors(context.Context, *Empty) (*GuildParts, error)
	mustEmbedUnimplementedGuildsServer()
}

// UnimplementedGuildsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGuildsServer struct{}

func (UnimplementedGuildsServer) GetBases(context.Context, *Empty) (*GuildParts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBases not implemented")
}
func (UnimplementedGuildsServer) GetSymbols(context.Context, *Empty) (*GuildParts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSymbols not implemented")
}
func (UnimplementedGuildsServer) GetBaseColors(context.Context, *Empty) (*GuildParts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBaseColors not implemented")
}
func (UnimplementedGuildsServer) GetSymbolColors(context.Context, *Empty) (*GuildParts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSymbolColors not implemented")
}
func (UnimplementedGuildsServer) GetBackgroundColors(context.Context, *Empty) (*GuildParts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBackgroundColors not implemented")
}
func (UnimplementedGuildsServer) mustEmbedUnimplementedGuildsServer() {}
func (UnimplementedGuildsServer) testEmbeddedByValue()                {}

// UnsafeGuildsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuildsServer will
// result in compilation errors.
type UnsafeGuildsServer interface {
	mustEmbedUnimplementedGuildsServer()
}

func RegisterGuildsServer(s grpc.ServiceRegistrar, srv GuildsServer) {
	// If the following call pancis, it indicates UnimplementedGuildsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Guilds_ServiceDesc, srv)
}

func _Guilds_GetBases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildsServer).GetBases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guilds_GetBases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildsServer).GetBases(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guilds_GetSymbols_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildsServer).GetSymbols(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guilds_GetSymbols_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildsServer).GetSymbols(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guilds_GetBaseColors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildsServer).GetBaseColors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guilds_GetBaseColors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildsServer).GetBaseColors(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guilds_GetSymbolColors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildsServer).GetSymbolColors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guilds_GetSymbolColors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildsServer).GetSymbolColors(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Guilds_GetBackgroundColors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildsServer).GetBackgroundColors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Guilds_GetBackgroundColors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildsServer).GetBackgroundColors(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Guilds_ServiceDesc is the grpc.ServiceDesc for Guilds service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Guilds_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "configuration.Guilds",
	HandlerType: (*GuildsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBases",
			Handler:    _Guilds_GetBases_Handler,
		},
		{
			MethodName: "GetSymbols",
			Handler:    _Guilds_GetSymbols_Handler,
		},
		{
			MethodName: "GetBaseColors",
			Handler:    _Guilds_GetBaseColors_Handler,
		},
		{
			MethodName: "GetSymbolColors",
			Handler:    _Guilds_GetSymbolColors_Handler,
		},
		{
			MethodName: "GetBackgroundColors",
			Handler:    _Guilds_GetBackgroundColors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guilds.proto",
}
