// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: guilds.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_guilds_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_guilds_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_guilds_proto_rawDescGZIP(), []int{0}
}

type GuildPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ValueA        string                 `protobuf:"bytes,2,opt,name=value_a,json=valueA,proto3" json:"value_a,omitempty"`
	ValueB        string                 `protobuf:"bytes,3,opt,name=value_b,json=valueB,proto3" json:"value_b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildPart) Reset() {
	*x = GuildPart{}
	mi := &file_guilds_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildPart) ProtoMessage() {}

func (x *GuildPart) ProtoReflect() protoreflect.Message {
	mi := &file_guilds_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildPart.ProtoReflect.Descriptor instead.
func (*GuildPart) Descriptor() ([]byte, []int) {
	return file_guilds_proto_rawDescGZIP(), []int{1}
}

func (x *GuildPart) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GuildPart) GetValueA() string {
	if x != nil {
		return x.ValueA
	}
	return ""
}

func (x *GuildPart) GetValueB() string {
	if x != nil {
		return x.ValueB
	}
	return ""
}

type GuildParts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parts         []*GuildPart           `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildParts) Reset() {
	*x = GuildParts{}
	mi := &file_guilds_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildParts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildParts) ProtoMessage() {}

func (x *GuildParts) ProtoReflect() protoreflect.Message {
	mi := &file_guilds_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildParts.ProtoReflect.Descriptor instead.
func (*GuildParts) Descriptor() ([]byte, []int) {
	return file_guilds_proto_rawDescGZIP(), []int{2}
}

func (x *GuildParts) GetParts() []*GuildPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

var File_guilds_proto protoreflect.FileDescriptor

const file_guilds_proto_rawDesc = "" +
	"\n" +
	"\fguilds.proto\x12\rconfiguration\"\a\n" +
	"\x05Empty\"M\n" +
	"\tGuildPart\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\avalue_a\x18\x02 \x01(\tR\x06valueA\x12\x17\n" +
	"\avalue_b\x18\x03 \x01(\tR\x06valueB\"<\n" +
	"\n" +
	"GuildParts\x12.\n" +
	"\x05parts\x18\x01 \x03(\v2\x18.configuration.GuildPartR\x05parts2\xdc\x02\n" +
	"\x06Guilds\x12=\n" +
	"\bGetBases\x12\x14.configuration.Empty\x1a\x19.configuration.GuildParts\"\x00\x12?\n" +
	"\n" +
	"GetSymbols\x12\x14.configuration.Empty\x1a\x19.configuration.GuildParts\"\x00\x12B\n" +
	"\rGetBaseColors\x12\x14.configuration.Empty\x1a\x19.configuration.GuildParts\"\x00\x12D\n" +
	"\x0fGetSymbolColors\x12\x14.configuration.Empty\x1a\x19.configuration.GuildParts\"\x00\x12H\n" +
	"\x13GetBackgroundColors\x12\x14.configuration.Empty\x1a\x19.configuration.GuildParts\"\x00B2Z0github.com/himalayo/clusterfuck/api/guilds/protob\x06proto3"

var (
	file_guilds_proto_rawDescOnce sync.Once
	file_guilds_proto_rawDescData []byte
)

func file_guilds_proto_rawDescGZIP() []byte {
	file_guilds_proto_rawDescOnce.Do(func() {
		file_guilds_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guilds_proto_rawDesc), len(file_guilds_proto_rawDesc)))
	})
	return file_guilds_proto_rawDescData
}

var file_guilds_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_guilds_proto_goTypes = []any{
	(*Empty)(nil),      // 0: configuration.Empty
	(*GuildPart)(nil),  // 1: configuration.GuildPart
	(*GuildParts)(nil), // 2: configuration.GuildParts
}
var file_guilds_proto_depIdxs = []int32{
	1, // 0: configuration.GuildParts.parts:type_name -> configuration.GuildPart
	0, // 1: configuration.Guilds.GetBases:input_type -> configuration.Empty
	0, // 2: configuration.Guilds.GetSymbols:input_type -> configuration.Empty
	0, // 3: configuration.Guilds.GetBaseColors:input_type -> configuration.Empty
	0, // 4: configuration.Guilds.GetSymbolColors:input_type -> configuration.Empty
	0, // 5: configuration.Guilds.GetBackgroundColors:input_type -> configuration.Empty
	2, // 6: configuration.Guilds.GetBases:output_type -> configuration.GuildParts
	2, // 7: configuration.Guilds.GetSymbols:output_type -> configuration.GuildParts
	2, // 8: configuration.Guilds.GetBaseColors:output_type -> configuration.GuildParts
	2, // 9: configuration.Guilds.GetSymbolColors:output_type -> configuration.GuildParts
	2, // 10: configuration.Guilds.GetBackgroundColors:output_type -> configuration.GuildParts
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_guilds_proto_init() }
func file_guilds_proto_init() {
	if File_guilds_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guilds_proto_rawDesc), len(file_guilds_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_guilds_proto_goTypes,
		DependencyIndexes: file_guilds_proto_depIdxs,
		MessageInfos:      file_guilds_proto_msgTypes,
	}.Build()
	File_guilds_proto = out.File
	file_guilds_proto_goTypes = nil
	file_guilds_proto_depIdxs = nil
}
