syntax = "proto3";

package achievements;

option go_package = "github.com/himalayo/clusterfuck/achievements/proto";

service Achievements {
    rpc GetAchievementByName (AchievementName) returns (Achievement) {}
    rpc GetAchievement (AchievementId) returns (Achievement) {}
    rpc InventoryAchievementsComposer (Empty) returns (Packet) {}
}


message Empty {}

message AchievementId {
    int32 id = 1;
}

message AchievementName {
    string name = 1;
}

message AchievementLevel {
    int32 level = 1;
    int32 reward_amount = 2;
    int32 reward_type = 3;
    int32 points = 4;
    int32 progress = 5;
}

enum AchievementCategory {
    IDENTITY = 0;
    EXPLORE = 1;
    MUSIC = 2;
    SOCIAL = 3;
    GAMES = 4;
    ROOM_BUILDER = 5;
    PETS = 6;
    TOOLS = 7;
    OTHER = 8;
    TEST = 9;
    INVISIBLE = 10;
    EVENTS = 11;
}

message Achievement {
    int32 id = 1;
    string name = 2;
    AchievementCategory category = 3;
    map<int32, AchievementLevel> levels = 4;
}

message Packet {
    bytes data = 1;
}
