// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: achievements.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AchievementCategory int32

const (
	AchievementCategory_IDENTITY     AchievementCategory = 0
	AchievementCategory_EXPLORE      AchievementCategory = 1
	AchievementCategory_MUSIC        AchievementCategory = 2
	AchievementCategory_SOCIAL       AchievementCategory = 3
	AchievementCategory_GAMES        AchievementCategory = 4
	AchievementCategory_ROOM_BUILDER AchievementCategory = 5
	AchievementCategory_PETS         AchievementCategory = 6
	AchievementCategory_TOOLS        AchievementCategory = 7
	AchievementCategory_OTHER        AchievementCategory = 8
	AchievementCategory_TEST         AchievementCategory = 9
	AchievementCategory_INVISIBLE    AchievementCategory = 10
	AchievementCategory_EVENTS       AchievementCategory = 11
)

// Enum value maps for AchievementCategory.
var (
	AchievementCategory_name = map[int32]string{
		0:  "IDENTITY",
		1:  "EXPLORE",
		2:  "MUSIC",
		3:  "SOCIAL",
		4:  "GAMES",
		5:  "ROOM_BUILDER",
		6:  "PETS",
		7:  "TOOLS",
		8:  "OTHER",
		9:  "TEST",
		10: "INVISIBLE",
		11: "EVENTS",
	}
	AchievementCategory_value = map[string]int32{
		"IDENTITY":     0,
		"EXPLORE":      1,
		"MUSIC":        2,
		"SOCIAL":       3,
		"GAMES":        4,
		"ROOM_BUILDER": 5,
		"PETS":         6,
		"TOOLS":        7,
		"OTHER":        8,
		"TEST":         9,
		"INVISIBLE":    10,
		"EVENTS":       11,
	}
)

func (x AchievementCategory) Enum() *AchievementCategory {
	p := new(AchievementCategory)
	*p = x
	return p
}

func (x AchievementCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AchievementCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_achievements_proto_enumTypes[0].Descriptor()
}

func (AchievementCategory) Type() protoreflect.EnumType {
	return &file_achievements_proto_enumTypes[0]
}

func (x AchievementCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AchievementCategory.Descriptor instead.
func (AchievementCategory) EnumDescriptor() ([]byte, []int) {
	return file_achievements_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_achievements_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_achievements_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_achievements_proto_rawDescGZIP(), []int{0}
}

type AchievementId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AchievementId) Reset() {
	*x = AchievementId{}
	mi := &file_achievements_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AchievementId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AchievementId) ProtoMessage() {}

func (x *AchievementId) ProtoReflect() protoreflect.Message {
	mi := &file_achievements_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AchievementId.ProtoReflect.Descriptor instead.
func (*AchievementId) Descriptor() ([]byte, []int) {
	return file_achievements_proto_rawDescGZIP(), []int{1}
}

func (x *AchievementId) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AchievementName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AchievementName) Reset() {
	*x = AchievementName{}
	mi := &file_achievements_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AchievementName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AchievementName) ProtoMessage() {}

func (x *AchievementName) ProtoReflect() protoreflect.Message {
	mi := &file_achievements_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AchievementName.ProtoReflect.Descriptor instead.
func (*AchievementName) Descriptor() ([]byte, []int) {
	return file_achievements_proto_rawDescGZIP(), []int{2}
}

func (x *AchievementName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AchievementLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	RewardAmount  int32                  `protobuf:"varint,2,opt,name=reward_amount,json=rewardAmount,proto3" json:"reward_amount,omitempty"`
	RewardType    int32                  `protobuf:"varint,3,opt,name=reward_type,json=rewardType,proto3" json:"reward_type,omitempty"`
	Points        int32                  `protobuf:"varint,4,opt,name=points,proto3" json:"points,omitempty"`
	Progress      int32                  `protobuf:"varint,5,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AchievementLevel) Reset() {
	*x = AchievementLevel{}
	mi := &file_achievements_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AchievementLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AchievementLevel) ProtoMessage() {}

func (x *AchievementLevel) ProtoReflect() protoreflect.Message {
	mi := &file_achievements_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AchievementLevel.ProtoReflect.Descriptor instead.
func (*AchievementLevel) Descriptor() ([]byte, []int) {
	return file_achievements_proto_rawDescGZIP(), []int{3}
}

func (x *AchievementLevel) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *AchievementLevel) GetRewardAmount() int32 {
	if x != nil {
		return x.RewardAmount
	}
	return 0
}

func (x *AchievementLevel) GetRewardType() int32 {
	if x != nil {
		return x.RewardType
	}
	return 0
}

func (x *AchievementLevel) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *AchievementLevel) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type Achievement struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Id            int32                       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      AchievementCategory         `protobuf:"varint,3,opt,name=category,proto3,enum=achievements.AchievementCategory" json:"category,omitempty"`
	Levels        map[int32]*AchievementLevel `protobuf:"bytes,4,rep,name=levels,proto3" json:"levels,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Achievement) Reset() {
	*x = Achievement{}
	mi := &file_achievements_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Achievement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Achievement) ProtoMessage() {}

func (x *Achievement) ProtoReflect() protoreflect.Message {
	mi := &file_achievements_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Achievement.ProtoReflect.Descriptor instead.
func (*Achievement) Descriptor() ([]byte, []int) {
	return file_achievements_proto_rawDescGZIP(), []int{4}
}

func (x *Achievement) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Achievement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Achievement) GetCategory() AchievementCategory {
	if x != nil {
		return x.Category
	}
	return AchievementCategory_IDENTITY
}

func (x *Achievement) GetLevels() map[int32]*AchievementLevel {
	if x != nil {
		return x.Levels
	}
	return nil
}

type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_achievements_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_achievements_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_achievements_proto_rawDescGZIP(), []int{5}
}

func (x *Packet) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_achievements_proto protoreflect.FileDescriptor

const file_achievements_proto_rawDesc = "" +
	"\n" +
	"\x12achievements.proto\x12\fachievements\"\a\n" +
	"\x05Empty\"\x1f\n" +
	"\rAchievementId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"%\n" +
	"\x0fAchievementName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xa2\x01\n" +
	"\x10AchievementLevel\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12#\n" +
	"\rreward_amount\x18\x02 \x01(\x05R\frewardAmount\x12\x1f\n" +
	"\vreward_type\x18\x03 \x01(\x05R\n" +
	"rewardType\x12\x16\n" +
	"\x06points\x18\x04 \x01(\x05R\x06points\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x05R\bprogress\"\x8a\x02\n" +
	"\vAchievement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12=\n" +
	"\bcategory\x18\x03 \x01(\x0e2!.achievements.AchievementCategoryR\bcategory\x12=\n" +
	"\x06levels\x18\x04 \x03(\v2%.achievements.Achievement.LevelsEntryR\x06levels\x1aY\n" +
	"\vLevelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.achievements.AchievementLevelR\x05value:\x028\x01\"\x1c\n" +
	"\x06Packet\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data*\xa9\x01\n" +
	"\x13AchievementCategory\x12\f\n" +
	"\bIDENTITY\x10\x00\x12\v\n" +
	"\aEXPLORE\x10\x01\x12\t\n" +
	"\x05MUSIC\x10\x02\x12\n" +
	"\n" +
	"\x06SOCIAL\x10\x03\x12\t\n" +
	"\x05GAMES\x10\x04\x12\x10\n" +
	"\fROOM_BUILDER\x10\x05\x12\b\n" +
	"\x04PETS\x10\x06\x12\t\n" +
	"\x05TOOLS\x10\a\x12\t\n" +
	"\x05OTHER\x10\b\x12\b\n" +
	"\x04TEST\x10\t\x12\r\n" +
	"\tINVISIBLE\x10\n" +
	"\x12\n" +
	"\n" +
	"\x06EVENTS\x10\v2\xfc\x01\n" +
	"\fAchievements\x12R\n" +
	"\x14GetAchievementByName\x12\x1d.achievements.AchievementName\x1a\x19.achievements.Achievement\"\x00\x12J\n" +
	"\x0eGetAchievement\x12\x1b.achievements.AchievementId\x1a\x19.achievements.Achievement\"\x00\x12L\n" +
	"\x1dInventoryAchievementsComposer\x12\x13.achievements.Empty\x1a\x14.achievements.Packet\"\x00B4Z2github.com/himalayo/clusterfuck/achievements/protob\x06proto3"

var (
	file_achievements_proto_rawDescOnce sync.Once
	file_achievements_proto_rawDescData []byte
)

func file_achievements_proto_rawDescGZIP() []byte {
	file_achievements_proto_rawDescOnce.Do(func() {
		file_achievements_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_achievements_proto_rawDesc), len(file_achievements_proto_rawDesc)))
	})
	return file_achievements_proto_rawDescData
}

var file_achievements_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_achievements_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_achievements_proto_goTypes = []any{
	(AchievementCategory)(0), // 0: achievements.AchievementCategory
	(*Empty)(nil),            // 1: achievements.Empty
	(*AchievementId)(nil),    // 2: achievements.AchievementId
	(*AchievementName)(nil),  // 3: achievements.AchievementName
	(*AchievementLevel)(nil), // 4: achievements.AchievementLevel
	(*Achievement)(nil),      // 5: achievements.Achievement
	(*Packet)(nil),           // 6: achievements.Packet
	nil,                      // 7: achievements.Achievement.LevelsEntry
}
var file_achievements_proto_depIdxs = []int32{
	0, // 0: achievements.Achievement.category:type_name -> achievements.AchievementCategory
	7, // 1: achievements.Achievement.levels:type_name -> achievements.Achievement.LevelsEntry
	4, // 2: achievements.Achievement.LevelsEntry.value:type_name -> achievements.AchievementLevel
	3, // 3: achievements.Achievements.GetAchievementByName:input_type -> achievements.AchievementName
	2, // 4: achievements.Achievements.GetAchievement:input_type -> achievements.AchievementId
	1, // 5: achievements.Achievements.InventoryAchievementsComposer:input_type -> achievements.Empty
	5, // 6: achievements.Achievements.GetAchievementByName:output_type -> achievements.Achievement
	5, // 7: achievements.Achievements.GetAchievement:output_type -> achievements.Achievement
	6, // 8: achievements.Achievements.InventoryAchievementsComposer:output_type -> achievements.Packet
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_achievements_proto_init() }
func file_achievements_proto_init() {
	if File_achievements_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_achievements_proto_rawDesc), len(file_achievements_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_achievements_proto_goTypes,
		DependencyIndexes: file_achievements_proto_depIdxs,
		EnumInfos:         file_achievements_proto_enumTypes,
		MessageInfos:      file_achievements_proto_msgTypes,
	}.Build()
	File_achievements_proto = out.File
	file_achievements_proto_goTypes = nil
	file_achievements_proto_depIdxs = nil
}
