// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: configuration.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Configuration_GetBoolean_FullMethodName = "/configuration.Configuration/GetBoolean"
	Configuration_GetInt_FullMethodName     = "/configuration.Configuration/GetInt"
	Configuration_GetDouble_FullMethodName  = "/configuration.Configuration/GetDouble"
	Configuration_GetString_FullMethodName  = "/configuration.Configuration/GetString"
)

// ConfigurationClient is the client API for Configuration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigurationClient interface {
	GetBoolean(ctx context.Context, in *ConfigurationRequest, opts ...grpc.CallOption) (*BooleanConfiguration, error)
	GetInt(ctx context.Context, in *ConfigurationRequest, opts ...grpc.CallOption) (*IntConfiguration, error)
	GetDouble(ctx context.Context, in *ConfigurationRequest, opts ...grpc.CallOption) (*DoubleConfiguration, error)
	GetString(ctx context.Context, in *ConfigurationRequest, opts ...grpc.CallOption) (*StringConfiguration, error)
}

type configurationClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigurationClient(cc grpc.ClientConnInterface) ConfigurationClient {
	return &configurationClient{cc}
}

func (c *configurationClient) GetBoolean(ctx context.Context, in *ConfigurationRequest, opts ...grpc.CallOption) (*BooleanConfiguration, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BooleanConfiguration)
	err := c.cc.Invoke(ctx, Configuration_GetBoolean_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationClient) GetInt(ctx context.Context, in *ConfigurationRequest, opts ...grpc.CallOption) (*IntConfiguration, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntConfiguration)
	err := c.cc.Invoke(ctx, Configuration_GetInt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationClient) GetDouble(ctx context.Context, in *ConfigurationRequest, opts ...grpc.CallOption) (*DoubleConfiguration, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoubleConfiguration)
	err := c.cc.Invoke(ctx, Configuration_GetDouble_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationClient) GetString(ctx context.Context, in *ConfigurationRequest, opts ...grpc.CallOption) (*StringConfiguration, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringConfiguration)
	err := c.cc.Invoke(ctx, Configuration_GetString_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigurationServer is the server API for Configuration service.
// All implementations must embed UnimplementedConfigurationServer
// for forward compatibility.
type ConfigurationServer interface {
	GetBoolean(context.Context, *ConfigurationRequest) (*BooleanConfiguration, error)
	GetInt(context.Context, *ConfigurationRequest) (*IntConfiguration, error)
	GetDouble(context.Context, *ConfigurationRequest) (*DoubleConfiguration, error)
	GetString(context.Context, *ConfigurationRequest) (*StringConfiguration, error)
	mustEmbedUnimplementedConfigurationServer()
}

// UnimplementedConfigurationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigurationServer struct{}

func (UnimplementedConfigurationServer) GetBoolean(context.Context, *ConfigurationRequest) (*BooleanConfiguration, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBoolean not implemented")
}
func (UnimplementedConfigurationServer) GetInt(context.Context, *ConfigurationRequest) (*IntConfiguration, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInt not implemented")
}
func (UnimplementedConfigurationServer) GetDouble(context.Context, *ConfigurationRequest) (*DoubleConfiguration, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDouble not implemented")
}
func (UnimplementedConfigurationServer) GetString(context.Context, *ConfigurationRequest) (*StringConfiguration, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetString not implemented")
}
func (UnimplementedConfigurationServer) mustEmbedUnimplementedConfigurationServer() {}
func (UnimplementedConfigurationServer) testEmbeddedByValue()                       {}

// UnsafeConfigurationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigurationServer will
// result in compilation errors.
type UnsafeConfigurationServer interface {
	mustEmbedUnimplementedConfigurationServer()
}

func RegisterConfigurationServer(s grpc.ServiceRegistrar, srv ConfigurationServer) {
	// If the following call pancis, it indicates UnimplementedConfigurationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Configuration_ServiceDesc, srv)
}

func _Configuration_GetBoolean_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServer).GetBoolean(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Configuration_GetBoolean_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServer).GetBoolean(ctx, req.(*ConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Configuration_GetInt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServer).GetInt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Configuration_GetInt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServer).GetInt(ctx, req.(*ConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Configuration_GetDouble_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServer).GetDouble(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Configuration_GetDouble_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServer).GetDouble(ctx, req.(*ConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Configuration_GetString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServer).GetString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Configuration_GetString_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServer).GetString(ctx, req.(*ConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Configuration_ServiceDesc is the grpc.ServiceDesc for Configuration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Configuration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "configuration.Configuration",
	HandlerType: (*ConfigurationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBoolean",
			Handler:    _Configuration_GetBoolean_Handler,
		},
		{
			MethodName: "GetInt",
			Handler:    _Configuration_GetInt_Handler,
		},
		{
			MethodName: "GetDouble",
			Handler:    _Configuration_GetDouble_Handler,
		},
		{
			MethodName: "GetString",
			Handler:    _Configuration_GetString_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "configuration.proto",
}
